// Package routers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package routers

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponseRole.
const (
	MeResponseRoleAdmin  MeResponseRole = "admin"
	MeResponseRoleMember MeResponseRole = "member"
)

// Valid indicates whether the value is a known member of the MeResponseRole enum.
func (e MeResponseRole) Valid() bool {
	switch e {
	case MeResponseRoleAdmin:
		return true
	case MeResponseRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for StoreMemberRole.
const (
	StoreMemberRoleManager StoreMemberRole = "manager"
	StoreMemberRoleMember  StoreMemberRole = "member"
)

// Valid indicates whether the value is a known member of the StoreMemberRole enum.
func (e StoreMemberRole) Valid() bool {
	switch e {
	case StoreMemberRoleManager:
		return true
	case StoreMemberRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for StoreReviewStatus.
const (
	Approved StoreReviewStatus = "approved"
	Pending  StoreReviewStatus = "pending"
	Rejected StoreReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the StoreReviewStatus enum.
func (e StoreReviewStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// AcceptStoreInvitationResponse defines model for AcceptStoreInvitationResponse.
type AcceptStoreInvitationResponse struct {
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// CreateMenuInput defines model for CreateMenuInput.
type CreateMenuInput struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image メニュー画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き
	Name string `json:"name"`

	// UnitPrice Example: 500
	UnitPrice int32 `json:"unitPrice"`
}

// CreateStoreApplicationResponse defines model for CreateStoreApplicationResponse.
type CreateStoreApplicationResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// CreateStoreInvitationResponse defines model for CreateStoreInvitationResponse.
type CreateStoreInvitationResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id 店舗メンバー招待のID。内部的にはstore_invitations.idと同一。
	Id openapi_types.UUID `json:"id"`

	// MaxUses 招待リンクの最大使用回数。nullの場合は無制限。
	MaxUses *int32             `json:"maxUses"`
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMenusByStoreIDResponse defines model for GetMenusByStoreIDResponse.
type GetMenusByStoreIDResponse struct {
	Data []Menu `json:"data"`

	// Total 店舗メニューの総数
	Total int `json:"total"`
}

// GetStoreApplicationsResponse defines model for GetStoreApplicationsResponse.
type GetStoreApplicationsResponse struct {
	Data []StoreApplication `json:"data"`

	// Total 店舗申請の総数
	Total int `json:"total"`
}

// GetStoreMembersResponse defines model for GetStoreMembersResponse.
type GetStoreMembersResponse struct {
	Data []StoreMember `json:"data"`

	// Total 店舗メンバーの総数
	Total int `json:"total"`
}

// GetVisibleStoresResponse defines model for GetVisibleStoresResponse.
type GetVisibleStoresResponse struct {
	Data []Store `json:"data"`

	// Total 閲覧可能な店舗の総数
	Total int `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	PictureUrl  *string             `json:"pictureUrl"`
	Role        MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Menu defines model for Menu.
type Menu struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    string             `json:"imageUrl"`
	Name        string             `json:"name"`
	SoldOut     bool               `json:"soldOut"`
	StoreId     openapi_types.UUID `json:"storeId"`
	UnitPrice   int32              `json:"unitPrice"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// Store defines model for Store.
type Store struct {
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
}

// StoreApplication defines model for StoreApplication.
type StoreApplication struct {
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// StoreMember defines model for StoreMember.
type StoreMember struct {
	AccountId   openapi_types.UUID `json:"accountId"`
	DisplayName string             `json:"displayName"`
	JoinedAt    time.Time          `json:"joinedAt"`
	PictureUrl  *string            `json:"pictureUrl"`
	Role        StoreMemberRole    `json:"role"`
	StoreId     openapi_types.UUID `json:"storeId"`
}

// StoreMemberRole defines model for StoreMemberRole.
type StoreMemberRole string

// StoreReviewStatus defines model for StoreReviewStatus.
type StoreReviewStatus string

// UpdateStoreApplicationReviewStatusResponse defines model for UpdateStoreApplicationReviewStatusResponse.
type UpdateStoreApplicationReviewStatusResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
}

// CreateStoreApplicationMultipartBody defines parameters for CreateStoreApplication.
type CreateStoreApplicationMultipartBody struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image 店舗画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き屋
	Name string `json:"name"`

	// Room Example: 605
	Room string `json:"room"`
}

// UpdateStoreApplicationReviewStatusJSONBody defines parameters for UpdateStoreApplicationReviewStatus.
type UpdateStoreApplicationReviewStatusJSONBody struct {
	ReviewStatus StoreReviewStatus `json:"reviewStatus"`
}

// CreateStoreInvitationJSONBody defines parameters for CreateStoreInvitation.
type CreateStoreInvitationJSONBody struct {
	// MaxUses 招待リンクの最大使用回数。省略時は無制限。
	MaxUses *int32          `json:"maxUses,omitempty"`
	Role    StoreMemberRole `json:"role"`
}

// CreateStoreApplicationMultipartRequestBody defines body for CreateStoreApplication for multipart/form-data ContentType.
type CreateStoreApplicationMultipartRequestBody CreateStoreApplicationMultipartBody

// UpdateStoreApplicationReviewStatusJSONRequestBody defines body for UpdateStoreApplicationReviewStatus for application/json ContentType.
type UpdateStoreApplicationReviewStatusJSONRequestBody UpdateStoreApplicationReviewStatusJSONBody

// CreateStoreInvitationJSONRequestBody defines body for CreateStoreInvitation for application/json ContentType.
type CreateStoreInvitationJSONRequestBody CreateStoreInvitationJSONBody

// CreateMenuMultipartRequestBody defines body for CreateMenu for multipart/form-data ContentType.
type CreateMenuMultipartRequestBody = CreateMenuInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(c *gin.Context)
	// GetMe ログイン中のアカウントを取得する
	// (GET /me)
	GetMe(c *gin.Context)
	// GetStoreApplications 店舗申請一覧を取得する
	// (GET /store-applications)
	GetStoreApplications(c *gin.Context)
	// CreateStoreApplication 店舗の作成申請を作成する
	// (POST /store-applications)
	CreateStoreApplication(c *gin.Context)
	// UpdateStoreApplicationReviewStatus 店舗申請の審査ステータスを更新する
	// (PUT /store-applications/review-status/{store_id})
	UpdateStoreApplicationReviewStatus(c *gin.Context, storeId openapi_types.UUID)
	// AcceptStoreInvitation 店舗のメンバー招待を受け入れる
	// (POST /store-invitations/{invitation_id}/accept)
	AcceptStoreInvitation(c *gin.Context, invitationId openapi_types.UUID)
	// GetVisibleStores 全ての承認済みの店舗と、自分が申請した店舗一覧を取得する
	// (GET /stores)
	GetVisibleStores(c *gin.Context)
	// GetApprovedStoreByID 承認済みの店舗を取得する
	// (GET /stores/{store_id})
	GetApprovedStoreByID(c *gin.Context, storeId openapi_types.UUID)
	// CreateStoreInvitation 店舗のメンバー招待を作成する
	// (POST /stores/{store_id}/invitations)
	CreateStoreInvitation(c *gin.Context, storeId openapi_types.UUID)
	// GetStoreMembers 店舗のメンバー一覧を取得する
	// (GET /stores/{store_id}/members)
	GetStoreMembers(c *gin.Context, storeId openapi_types.UUID)
	// GetMenusByStoreID 店舗のメニュー一覧を取得する
	// (GET /stores/{store_id}/menus)
	GetMenusByStoreID(c *gin.Context, storeId openapi_types.UUID)
	// CreateMenu 店舗のメニューを作成する
	// (POST /stores/{store_id}/menus)
	CreateMenu(c *gin.Context, storeId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetStoreApplications operation middleware
func (siw *ServerInterfaceWrapper) GetStoreApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreApplications(c)
}

// CreateStoreApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreApplication(c)
}

// UpdateStoreApplicationReviewStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateStoreApplicationReviewStatus(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStoreApplicationReviewStatus(c, storeId)
}

// AcceptStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "invitation_id" -------------
	var invitationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", c.Param("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invitation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptStoreInvitation(c, invitationId)
}

// GetVisibleStores operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleStores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVisibleStores(c)
}

// GetApprovedStoreByID operation middleware
func (siw *ServerInterfaceWrapper) GetApprovedStoreByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApprovedStoreByID(c, storeId)
}

// CreateStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreInvitation(c, storeId)
}

// GetStoreMembers operation middleware
func (siw *ServerInterfaceWrapper) GetStoreMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreMembers(c, storeId)
}

// GetMenusByStoreID operation middleware
func (siw *ServerInterfaceWrapper) GetMenusByStoreID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMenusByStoreID(c, storeId)
}

// CreateMenu operation middleware
func (siw *ServerInterfaceWrapper) CreateMenu(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMenu(c, storeId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/store-applications", wrapper.GetStoreApplications)
	router.POST(options.BaseURL+"/store-applications", wrapper.CreateStoreApplication)
	router.PUT(options.BaseURL+"/store-applications/review-status/:store_id", wrapper.UpdateStoreApplicationReviewStatus)
	router.GET(options.BaseURL+"/stores", wrapper.GetVisibleStores)
	router.GET(options.BaseURL+"/stores/:store_id", wrapper.GetApprovedStoreByID)
	router.GET(options.BaseURL+"/stores/:store_id/members", wrapper.GetStoreMembers)
	router.GET(options.BaseURL+"/stores/:store_id/menus", wrapper.GetMenusByStoreID)
	router.POST(options.BaseURL+"/stores/:store_id/menus", wrapper.CreateMenu)
	router.POST(options.BaseURL+"/stores/:store_id/invitations", wrapper.CreateStoreInvitation)
	router.POST(options.BaseURL+"/store-invitations/:invitation_id/accept", wrapper.AcceptStoreInvitation)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftvc9NGGv8qnb176cQOgZue38HR6XE9WgaGuxc0w2zsDVmw/py0pngYz3ilhDMkOXIcIZcjUwoFEpJi",
	"00LbAAE+zEZ28oqvcLMryZYsyXISxzg0bzKJIj37/P09f/ToKsgokqrISCY6SF8FemYcSVD8ejSTQSo5",
	"QxQNnZAvYwIJVuTTSFcVWUf8BlVTVKQRjMTtmpITV3+voTGQBr9LNgknHapJQewkkkaRdprfXkwAXdDP",
	"8ifHFE2CBKRBPo+zIAFIQUUgDXSiYfkCKBYTQEP/yGMNZUH6XOPBhH3ySON+ZfQiyhBO+08aggSdRHL+",
	"hKzmSZDnLNIzGla5YPxPdAVKKpcCWA/vMFplxiozV5yfJbqx9pRfNMvMfOr8pBVG7zH6n/rEOqMzjC4x",
	"usBKBkgACV75K5IvkHGQHkqlUgkgYblxISBbAmAJXkABngAz7zNzipmPmLlev/3aMm+ykvGXU599zkr0",
	"1Jf859/R6ClGV63qW+vdIj/emGIl42u5tliyHi4xc44Z95nxkJmrzPiZ/2K8YrQ6lDp5TNwGEk29j2IZ",
	"agUQwp0MJeTXkFfugLix0uZlTE5pOOMneoQ/2eAGy2T4EBCksJSXQDrVIIRlgi4gLeATgs2ET4Xes1wt",
	"R/uKcNCjqprDmRh3x9mgsaxX85vl+frt55urU4xWThxnJcO6NrllLtf/N8HoKqNV4bX6IM4yumzNTm+s",
	"lQJWCPd+LuhljL45QyDJ6x0F2mnvAzzU8qMSJgRljxJfuGUhQQMEC9W1jznBmI8PP9UYxXYCIxlx+zZY",
	"TLQxhYie58ycZeZ6bequ9XaynVnO4wZ/O7OQBK+c1UOQBThnmyucG6PKaMWOzo037+q3l62739bmnrGS",
	"IedzOUYr1ncvrNkyo9X6xH2r/MvWwqwNKYHI4PfDUR45RMujYHQkeg7K4pYWZG7qJeGxbpirfKZpihbt",
	"GhLSdQck23Ph3hh2xueI8ISgHyvYLnk8+rwsJFCEOkFSbMRxopy+cyDUNFgQfysE5tr6p4PujFbqv96s",
	"zT0DsTAnGHNJRwjZimR6l+RspbttmRvw2HVpbR/uqqA2yZ3Z1cGdLkv6N6zj0ZyNp10VdRtCbt35afPx",
	"knWzumm+YXTFkbmLcv4ZwRwZj5ZObyTBZkGiXOqgZBSPhZ14ErXRJdbVHCx86dRAAdhHEsQ5H1baVyJT",
	"VWwiUXGG5DV0VhNkI2DeUxk4KI9kXiZx/BNemwAwK2HZI2871HZ59krr46RNoS3ArxupvKUg36n+RJnn",
	"aC+ylg38Q1dy2a/sNsH536ii5BCUt5cSW6rbQNYOZum8moW7LsuaWbezKtg2qSuzl4m4NG3DRVwz1Vvb",
	"7bo41hRFiq8ssEe/4olWNXtU62MpUo/eVPrbUGnXGpGd2CG+X/Hm/YBBYCaj5GXSIQ7EJY6LCpa3h487",
	"TAy9n8k0FdXoAhrStskxMQY5HZXoJChDDqYjIUoI+qaHgorkLL8vAaCqasplZHe4/GyUDSV3VuBkcFDQ",
	"pP8RDQ1i+/+gwbj/oExew6RwhhNG7jCR+8MZpOsOmGEufEZRLmHkxnIaYD1zfgzp5x33Oa879zdLUxV/",
	"gQqgyI/B8pgi4gqTnPPwwBjSPzl66gRIgMtIs48CqcGhwRRXhqIiGaoYpMHwYGpwmLseJOOCv+S4KDn5",
	"rxeQCEhuN2FaHgi88raLUqEA277iwUOplKh1FJkgWTwIm16RvKjbwtoqjjNAS9krhPQ7y1df8KvFBEja",
	"kBLF60m0l3x6iuUQHpn5lBnPxMjxuRiZVpjxgBmrzHgsmqIyN8Xh1FDX2PGPDUI4qi2ueJli9K2YXlaZ",
	"8ZqZJjN+ZeaSuD5dn7hv3XjJGTzSRX3FMsiMn3mnaPeLxjIznzBz3RdKIH0uGETnRoojPKFJEtQKnWie",
	"Gbesm3est/P2nFickBToMuCRTm/nWYG5wl46Wts5RogevVi6sVbafLz0oX3NPn+4d+fXK/frs9c2S5O1",
	"5SdbC7OMTjO6wujEfvXpoEkDTpwAqqKHeGv4SB/YKQ3p5JiSLbToQ8rnCFahRpI8sw64U5SmSvbb+yNX",
	"fX365sj6cWr7L4/cvqJB8g+pIz4iR+JohL82im4kwsocHw1efxcDQNg92Il5OxUDhcy4tfFmsVaeZXSe",
	"0Xs2JvUSCngQVDkIGC+ZWbbePLDWbzI6vbE2U3v6fV9A9NBwL5HxAS87zHmBA+vMvM7oHDOmGb3nBCqd",
	"5gHIAWGB0X85IHd46EjveHRBYZ7Rx4xO2DnE5s42n+Do0KEecjT5yLpx1yo9bJRvrrIq1rVJq/LS51D9",
	"kOo4F73M/LY6RIgx8wfBy5pQSqm2YNjNpFV+Ur+9LPLMjFsX7CwjM1qxMSUAMe0qy6TdPA7Yk/jkVee9",
	"a7Yocms+JInHt9uijdOghAjSdCGBaC15a9dsLN2DQCtqJzzqjxt2jLQrHdpbtmVXpqtdeVxD3kGm6l6w",
	"bGM8Epe1aMWqPqndey1c+prw53f8d+NW7e6L2p1nB9ms3xuOw6nDPUwQPt+Ztp7+11pcFj7SZOePPbSL",
	"46NNqA33ZrrGHf3h9drdF5+4M8hPBr7Op1LDqHlBUHjyMTRxHYR1awbx7OUkrzb/4HkjCcWWooDY0CYw",
	"dIuxo5ThO2j3eWOPOoP2W5qRYcI7z+ByFO+s5xn9tzX5yK5HD8A1BFx7iGnu0lormrES9e2OcQXdEOi7",
	"ukVvN8t2p3PoJe6JnmWJ15phjib+ZTh87V8o6yh8fCDWdqjqW+rZ44Fq+AJRmO9df7e5MlNbKzP6joO2",
	"I/gyK9HNf65Y5WuMTruQzgsx+4bm2LVfrNs03eSyCIvKbiSLHqG3tjNRxj7q5HRhgWOFE8d73MDskWs5",
	"S2RRCadmTlrf/diX+aTnNWoonjfGGn7vXGK02n8T/EZMhYdSRzGS9JR10fVb6Pr4Pmz5d7sbXl+k9blH",
	"tQWjg73wxhcTQ3u2I946ggjfDPxgQ/JulMIHI/P+GTLYs4WNtZnNX56/Xy+7W9bfMnPGmXOa37vVJcfK",
	"9+vX+wfb6RQr0ehquPoxvKCNC6J2ecDe4orfOnD2+z+Ocinqo4VOYcq73nCASx+qP++knvttRf52uqSk",
	"hOS83n6Pzfup1kcT+RFfoMXGvvOpWB/H/kEvtYv5RLStt7nzJL7H6Y8eKXajKr6ib37A3+OGwv6ms8Og",
	"POgY9kHHEJKEI9L1/ugt3q+Xa4srNsp5JpnVFsesL7zemv7J+y7SFeJg7+lg76m/6sggnDoVpCCrXXaz",
	"WfCjA/7QKjNXt+5M1Rde1W89sx6YIAHyWg6kwTghajqZzCkZmBtXdJL+NPVpChQTgXHc4g/1uZWQh/V0",
	"MglVPDiG9EH8DdThJTwIM4MXVVAcKf4/AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
