// Package routers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package routers

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponseRole.
const (
	Admin  MeResponseRole = "admin"
	Member MeResponseRole = "member"
)

// Valid indicates whether the value is a known member of the MeResponseRole enum.
func (e MeResponseRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Defines values for StoreMemberRole.
const (
	Manager StoreMemberRole = "manager"
	Staff   StoreMemberRole = "staff"
)

// Valid indicates whether the value is a known member of the StoreMemberRole enum.
func (e StoreMemberRole) Valid() bool {
	switch e {
	case Manager:
		return true
	case Staff:
		return true
	default:
		return false
	}
}

// Defines values for StoreReviewStatus.
const (
	Approved StoreReviewStatus = "approved"
	Pending  StoreReviewStatus = "pending"
	Rejected StoreReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the StoreReviewStatus enum.
func (e StoreReviewStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// AcceptStoreInvitationResponse defines model for AcceptStoreInvitationResponse.
type AcceptStoreInvitationResponse struct {
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// Allergen defines model for Allergen.
type Allergen struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// Cart defines model for Cart.
type Cart struct {
	// CanCheckout カートの内容で注文可能かどうか。店舗が閉店している場合、カートに利用できないアイテムが含まれている場合、カートがからの場合はfalseになる。
	CanCheckout bool               `json:"canCheckout"`
	Items       []CartItem         `json:"items"`
	StoreId     openapi_types.UUID `json:"storeId"`
	TotalAmount int                `json:"totalAmount"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	// Available メニューが現在利用可能かどうか。店舗がメニューを削除した場合や売り切れはfalseになる。
	Available bool                `json:"available"`
	Id        openapi_types.UUID  `json:"id"`
	ImageUrl  string              `json:"imageUrl"`
	MenuId    openapi_types.UUID  `json:"menuId"`
	Name      string              `json:"name"`
	Quantity  int32               `json:"quantity"`
	StoreId   *openapi_types.UUID `json:"storeId,omitempty"`
	Toppings  []CartItemTopping   `json:"toppings"`
	UnitPrice int32               `json:"unitPrice"`
}

// CartItemTopping defines model for CartItemTopping.
type CartItemTopping struct {
	// Available トッピングが現在利用可能かどうか。店舗がトッピングを削除した場合や在庫切れはfalseになる。
	Available  bool                `json:"available"`
	CartItemId *openapi_types.UUID `json:"cartItemId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	MenuId     openapi_types.UUID  `json:"menuId"`
	Name       string              `json:"name"`
	ToppingId  openapi_types.UUID  `json:"toppingId"`
	UnitPrice  int32               `json:"unitPrice"`
}

// CreateMenuInput defines model for CreateMenuInput.
type CreateMenuInput struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image メニュー画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き
	Name string `json:"name"`

	// ToppingIds 対象のメニューにトッピング可能なトッピングのID一覧。空配列も可。
	ToppingIds *[]openapi_types.UUID `json:"toppingIds,omitempty"`

	// UnitPrice Example: 500
	UnitPrice int32 `json:"unitPrice"`
}

// CreateStoreApplicationResponse defines model for CreateStoreApplicationResponse.
type CreateStoreApplicationResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// CreateStoreInvitationResponse defines model for CreateStoreInvitationResponse.
type CreateStoreInvitationResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id 店舗メンバー招待のID。内部的にはstore_invitations.idと同一。
	Id openapi_types.UUID `json:"id"`

	// MaxUses 招待リンクの最大使用回数。nullの場合は無制限。
	MaxUses *int32             `json:"maxUses"`
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// CreateToppingInput defines model for CreateToppingInput.
type CreateToppingInput struct {
	// Name Example: チーズ
	Name string `json:"name"`

	// UnitPrice Example: 100
	UnitPrice int32 `json:"unitPrice"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetAllergensResponse defines model for GetAllergensResponse.
type GetAllergensResponse struct {
	Data []Allergen `json:"data"`

	// Total アレルゲンの総数
	Total int `json:"total"`
}

// GetMenusByStoreIDResponse defines model for GetMenusByStoreIDResponse.
type GetMenusByStoreIDResponse struct {
	Data []Menu `json:"data"`

	// Total 店舗メニューの総数
	Total int `json:"total"`
}

// GetRoomsResponse defines model for GetRoomsResponse.
type GetRoomsResponse struct {
	Data []Room `json:"data"`

	// Total ルームの総数
	Total int `json:"total"`
}

// GetStoreApplicationsResponse defines model for GetStoreApplicationsResponse.
type GetStoreApplicationsResponse struct {
	Data []StoreApplication `json:"data"`

	// Total 店舗申請の総数
	Total int `json:"total"`
}

// GetStoreMembersResponse defines model for GetStoreMembersResponse.
type GetStoreMembersResponse struct {
	Data []StoreMember `json:"data"`

	// Total 店舗メンバーの総数
	Total int `json:"total"`
}

// GetToppingsByStoreIDResponse defines model for GetToppingsByStoreIDResponse.
type GetToppingsByStoreIDResponse struct {
	Data []Topping `json:"data"`

	// Total 店舗トッピングの総数
	Total int `json:"total"`
}

// GetVisibleStoresResponse defines model for GetVisibleStoresResponse.
type GetVisibleStoresResponse struct {
	Data []Store `json:"data"`

	// Total 閲覧可能な店舗の総数
	Total int `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// CommitHash 稼働中のイメージの元となったGit Commit SHA
	//
	// Example: 0123456789abcdef0123456789abcdef01234567
	CommitHash string `json:"commitHash"`

	// DeployedAt デプロイされた日時（正確にはビルドされた日時だが、最大でも数分程度の誤差のはず）
	//
	// Example: 2026-08-29T12:34:56Z
	DeployedAt time.Time `json:"deployedAt"`

	// Status Example: ok
	Status string `json:"status"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	PictureUrl  *string             `json:"pictureUrl"`
	Role        MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Menu defines model for Menu.
type Menu struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    string             `json:"imageUrl"`
	Name        string             `json:"name"`
	SoldOut     bool               `json:"soldOut"`
	StoreId     openapi_types.UUID `json:"storeId"`
	UnitPrice   int32              `json:"unitPrice"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// Room defines model for Room.
type Room struct {
	Name string `json:"name"`
}

// Store defines model for Store.
type Store struct {
	Allergens    []Allergen         `json:"allergens"`
	ClosedAt     *time.Time         `json:"closedAt"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
}

// StoreApplication defines model for StoreApplication.
type StoreApplication struct {
	Allergens    []Allergen         `json:"allergens"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// StoreMember defines model for StoreMember.
type StoreMember struct {
	AccountId   openapi_types.UUID `json:"accountId"`
	DisplayName string             `json:"displayName"`
	JoinedAt    time.Time          `json:"joinedAt"`
	PictureUrl  *string            `json:"pictureUrl"`
	Role        StoreMemberRole    `json:"role"`
	StoreId     openapi_types.UUID `json:"storeId"`
}

// StoreMemberRole defines model for StoreMemberRole.
type StoreMemberRole string

// StoreReviewStatus defines model for StoreReviewStatus.
type StoreReviewStatus string

// Topping defines model for Topping.
type Topping struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	SoldOut   bool               `json:"soldOut"`
	StoreId   openapi_types.UUID `json:"storeId"`
	UnitPrice int32              `json:"unitPrice"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// UpdateMenuInput defines model for UpdateMenuInput.
type UpdateMenuInput struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description *string `json:"description,omitempty"`

	// Image メニュー画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image *openapi_types.File `json:"image,omitempty"`

	// Name Example: たこ焼き
	Name *string `json:"name,omitempty"`

	// ToppingIds 対象のメニューにトッピング可能なトッピングのID一覧。空配列も可。
	ToppingIds *[]openapi_types.UUID `json:"toppingIds,omitempty"`

	// UnitPrice Example: 500
	UnitPrice *int32 `json:"unitPrice,omitempty"`
}

// UpdateStoreApplicationReviewStatusResponse defines model for UpdateStoreApplicationReviewStatusResponse.
type UpdateStoreApplicationReviewStatusResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
}

// UpdateToppingInput defines model for UpdateToppingInput.
type UpdateToppingInput struct {
	// Name Example: チーズ
	Name    string `json:"name"`
	SoldOut bool   `json:"soldOut"`

	// UnitPrice Example: 100
	UnitPrice int32 `json:"unitPrice"`
}

// CreateStoreApplicationMultipartBody defines parameters for CreateStoreApplication.
type CreateStoreApplicationMultipartBody struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image 店舗画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き屋
	Name string `json:"name"`

	// Room Example: 605
	Room string `json:"room"`
}

// UpdateStoreApplicationReviewStatusJSONBody defines parameters for UpdateStoreApplicationReviewStatus.
type UpdateStoreApplicationReviewStatusJSONBody struct {
	ReviewStatus StoreReviewStatus `json:"reviewStatus"`
}

// CreateStoreInvitationJSONBody defines parameters for CreateStoreInvitation.
type CreateStoreInvitationJSONBody struct {
	// MaxUses 招待リンクの最大使用回数。省略時は無制限。
	MaxUses *int32          `json:"maxUses,omitempty"`
	Role    StoreMemberRole `json:"role"`
}

// CreateStoreApplicationMultipartRequestBody defines body for CreateStoreApplication for multipart/form-data ContentType.
type CreateStoreApplicationMultipartRequestBody CreateStoreApplicationMultipartBody

// UpdateStoreApplicationReviewStatusJSONRequestBody defines body for UpdateStoreApplicationReviewStatus for application/json ContentType.
type UpdateStoreApplicationReviewStatusJSONRequestBody UpdateStoreApplicationReviewStatusJSONBody

// CreateStoreInvitationJSONRequestBody defines body for CreateStoreInvitation for application/json ContentType.
type CreateStoreInvitationJSONRequestBody CreateStoreInvitationJSONBody

// CreateMenuMultipartRequestBody defines body for CreateMenu for multipart/form-data ContentType.
type CreateMenuMultipartRequestBody = CreateMenuInput

// UpdateMenuByStoreIDAndMenuIDMultipartRequestBody defines body for UpdateMenuByStoreIDAndMenuID for multipart/form-data ContentType.
type UpdateMenuByStoreIDAndMenuIDMultipartRequestBody = UpdateMenuInput

// CreateToppingJSONRequestBody defines body for CreateTopping for application/json ContentType.
type CreateToppingJSONRequestBody = CreateToppingInput

// UpdateToppingByStoreIDAndToppingIDJSONRequestBody defines body for UpdateToppingByStoreIDAndToppingID for application/json ContentType.
type UpdateToppingByStoreIDAndToppingIDJSONRequestBody = UpdateToppingInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAllergens アレルゲン一覧を取得する
	// (GET /allergens)
	GetAllergens(c *gin.Context)

	// (GET /health)
	GetHealth(c *gin.Context)
	// GetMe ログイン中のアカウントを取得する
	// (GET /me)
	GetMe(c *gin.Context)
	// GetRooms 利用可能な教室一覧を取得する
	// (GET /rooms)
	GetRooms(c *gin.Context)
	// GetStoreApplications 店舗申請一覧を取得する
	// (GET /store-applications)
	GetStoreApplications(c *gin.Context)
	// CreateStoreApplication 店舗の作成申請を作成する
	// (POST /store-applications)
	CreateStoreApplication(c *gin.Context)
	// UpdateStoreApplicationReviewStatus 店舗申請の審査ステータスを更新する
	// (PUT /store-applications/review-status/{store_id})
	UpdateStoreApplicationReviewStatus(c *gin.Context, storeId openapi_types.UUID)
	// AcceptStoreInvitation 店舗のメンバー招待を受け入れる
	// (POST /store-invitations/{invitation_id}/accept)
	AcceptStoreInvitation(c *gin.Context, invitationId openapi_types.UUID)
	// GetVisibleStores 全ての承認済みの店舗と、自分が申請した店舗一覧を取得する
	// (GET /stores)
	GetVisibleStores(c *gin.Context)
	// GetApprovedStoreByID 承認済みの店舗を取得する
	// (GET /stores/{store_id})
	GetApprovedStoreByID(c *gin.Context, storeId openapi_types.UUID)
	// GetStoreCart 店舗の自分のカートを取得する（Guest セッションがない場合は空カートが返る）
	// (GET /stores/{store_id}/carts)
	GetStoreCart(c *gin.Context, storeId openapi_types.UUID)
	// CreateStoreInvitation 店舗のメンバー招待を作成する
	// (POST /stores/{store_id}/invitations)
	CreateStoreInvitation(c *gin.Context, storeId openapi_types.UUID)
	// GetStoreMembers 店舗のメンバー一覧を取得する
	// (GET /stores/{store_id}/members)
	GetStoreMembers(c *gin.Context, storeId openapi_types.UUID)
	// RemoveStoreMember 店舗のメンバーを削除する
	// (DELETE /stores/{store_id}/members/{account_id})
	RemoveStoreMember(c *gin.Context, storeId openapi_types.UUID, accountId openapi_types.UUID)
	// GetStoreMemberByStoreIDAndAccountID 店舗のメンバーを取得する
	// (GET /stores/{store_id}/members/{account_id})
	GetStoreMemberByStoreIDAndAccountID(c *gin.Context, storeId openapi_types.UUID, accountId openapi_types.UUID)
	// GetMenusByStoreID 店舗のメニュー一覧を取得する
	// (GET /stores/{store_id}/menus)
	GetMenusByStoreID(c *gin.Context, storeId openapi_types.UUID)
	// CreateMenu 店舗のメニューを作成する
	// (POST /stores/{store_id}/menus)
	CreateMenu(c *gin.Context, storeId openapi_types.UUID)
	// DeleteMenuByStoreIDAndMenuID 店舗のメニューを削除する
	// (DELETE /stores/{store_id}/menus/{menu_id})
	DeleteMenuByStoreIDAndMenuID(c *gin.Context, storeId openapi_types.UUID, menuId openapi_types.UUID)
	// UpdateMenuByStoreIDAndMenuID 店舗のメニューを更新する
	// (PUT /stores/{store_id}/menus/{menu_id})
	UpdateMenuByStoreIDAndMenuID(c *gin.Context, storeId openapi_types.UUID, menuId openapi_types.UUID)
	// GetToppingsByStoreID 店舗のトッピング一覧を取得する
	// (GET /stores/{store_id}/toppings)
	GetToppingsByStoreID(c *gin.Context, storeId openapi_types.UUID)
	// CreateTopping 店舗のトッピングを作成する
	// (POST /stores/{store_id}/toppings)
	CreateTopping(c *gin.Context, storeId openapi_types.UUID)
	// DeleteToppingByStoreIDAndToppingID 店舗のトッピングを削除する（紐づけられているメニューのトッピングも削除される）
	// (DELETE /stores/{store_id}/toppings/{topping_id})
	DeleteToppingByStoreIDAndToppingID(c *gin.Context, storeId openapi_types.UUID, toppingId openapi_types.UUID)
	// UpdateToppingByStoreIDAndToppingID 店舗のトッピングを更新する
	// (PUT /stores/{store_id}/toppings/{topping_id})
	UpdateToppingByStoreIDAndToppingID(c *gin.Context, storeId openapi_types.UUID, toppingId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAllergens operation middleware
func (siw *ServerInterfaceWrapper) GetAllergens(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllergens(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetRooms operation middleware
func (siw *ServerInterfaceWrapper) GetRooms(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRooms(c)
}

// GetStoreApplications operation middleware
func (siw *ServerInterfaceWrapper) GetStoreApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreApplications(c)
}

// CreateStoreApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreApplication(c)
}

// UpdateStoreApplicationReviewStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateStoreApplicationReviewStatus(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStoreApplicationReviewStatus(c, storeId)
}

// AcceptStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "invitation_id" -------------
	var invitationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", c.Param("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invitation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptStoreInvitation(c, invitationId)
}

// GetVisibleStores operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleStores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVisibleStores(c)
}

// GetApprovedStoreByID operation middleware
func (siw *ServerInterfaceWrapper) GetApprovedStoreByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApprovedStoreByID(c, storeId)
}

// GetStoreCart operation middleware
func (siw *ServerInterfaceWrapper) GetStoreCart(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreCart(c, storeId)
}

// CreateStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreInvitation(c, storeId)
}

// GetStoreMembers operation middleware
func (siw *ServerInterfaceWrapper) GetStoreMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreMembers(c, storeId)
}

// RemoveStoreMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveStoreMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveStoreMember(c, storeId, accountId)
}

// GetStoreMemberByStoreIDAndAccountID operation middleware
func (siw *ServerInterfaceWrapper) GetStoreMemberByStoreIDAndAccountID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter account_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreMemberByStoreIDAndAccountID(c, storeId, accountId)
}

// GetMenusByStoreID operation middleware
func (siw *ServerInterfaceWrapper) GetMenusByStoreID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMenusByStoreID(c, storeId)
}

// CreateMenu operation middleware
func (siw *ServerInterfaceWrapper) CreateMenu(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMenu(c, storeId)
}

// DeleteMenuByStoreIDAndMenuID operation middleware
func (siw *ServerInterfaceWrapper) DeleteMenuByStoreIDAndMenuID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "menu_id" -------------
	var menuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "menu_id", c.Param("menu_id"), &menuId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter menu_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMenuByStoreIDAndMenuID(c, storeId, menuId)
}

// UpdateMenuByStoreIDAndMenuID operation middleware
func (siw *ServerInterfaceWrapper) UpdateMenuByStoreIDAndMenuID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "menu_id" -------------
	var menuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "menu_id", c.Param("menu_id"), &menuId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter menu_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMenuByStoreIDAndMenuID(c, storeId, menuId)
}

// GetToppingsByStoreID operation middleware
func (siw *ServerInterfaceWrapper) GetToppingsByStoreID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetToppingsByStoreID(c, storeId)
}

// CreateTopping operation middleware
func (siw *ServerInterfaceWrapper) CreateTopping(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTopping(c, storeId)
}

// DeleteToppingByStoreIDAndToppingID operation middleware
func (siw *ServerInterfaceWrapper) DeleteToppingByStoreIDAndToppingID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "topping_id" -------------
	var toppingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "topping_id", c.Param("topping_id"), &toppingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter topping_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteToppingByStoreIDAndToppingID(c, storeId, toppingId)
}

// UpdateToppingByStoreIDAndToppingID operation middleware
func (siw *ServerInterfaceWrapper) UpdateToppingByStoreIDAndToppingID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "topping_id" -------------
	var toppingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "topping_id", c.Param("topping_id"), &toppingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter topping_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateToppingByStoreIDAndToppingID(c, storeId, toppingId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/rooms", wrapper.GetRooms)
	router.GET(options.BaseURL+"/store-applications", wrapper.GetStoreApplications)
	router.POST(options.BaseURL+"/store-applications", wrapper.CreateStoreApplication)
	router.PUT(options.BaseURL+"/store-applications/review-status/:store_id", wrapper.UpdateStoreApplicationReviewStatus)
	router.GET(options.BaseURL+"/stores", wrapper.GetVisibleStores)
	router.GET(options.BaseURL+"/stores/:store_id", wrapper.GetApprovedStoreByID)
	router.GET(options.BaseURL+"/stores/:store_id/members", wrapper.GetStoreMembers)
	router.DELETE(options.BaseURL+"/stores/:store_id/members/:account_id", wrapper.RemoveStoreMember)
	router.GET(options.BaseURL+"/stores/:store_id/members/:account_id", wrapper.GetStoreMemberByStoreIDAndAccountID)
	router.GET(options.BaseURL+"/stores/:store_id/menus", wrapper.GetMenusByStoreID)
	router.POST(options.BaseURL+"/stores/:store_id/menus", wrapper.CreateMenu)
	router.DELETE(options.BaseURL+"/stores/:store_id/menus/:menu_id", wrapper.DeleteMenuByStoreIDAndMenuID)
	router.PUT(options.BaseURL+"/stores/:store_id/menus/:menu_id", wrapper.UpdateMenuByStoreIDAndMenuID)
	router.GET(options.BaseURL+"/stores/:store_id/toppings", wrapper.GetToppingsByStoreID)
	router.POST(options.BaseURL+"/stores/:store_id/toppings", wrapper.CreateTopping)
	router.DELETE(options.BaseURL+"/stores/:store_id/toppings/:topping_id", wrapper.DeleteToppingByStoreIDAndToppingID)
	router.PUT(options.BaseURL+"/stores/:store_id/toppings/:topping_id", wrapper.UpdateToppingByStoreIDAndToppingID)
	router.POST(options.BaseURL+"/stores/:store_id/invitations", wrapper.CreateStoreInvitation)
	router.GET(options.BaseURL+"/stores/:store_id/carts", wrapper.GetStoreCart)
	router.POST(options.BaseURL+"/store-invitations/:invitation_id/accept", wrapper.AcceptStoreInvitation)
	router.GET(options.BaseURL+"/allergens", wrapper.GetAllergens)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1rc9NGv/8qjM556cROAhzqd6F0KKeHloH2PDNPyzCKvUkEtqRKMiWTYcYrkeCQ5CGlhDwpmXIL5FZi",
	"bm3TEODDbGQnr/gKz+yuJOsuOXEcJ/hNMLa0+u//8vvfdlfDTEbIiwIPeEVm0sOMnBkEeZZ87M1kgKhc",
	"UAQJnOGvcgqrcAJ/HsiiwMsAXyBKgggkhQPkcknIkW//WwL9TJr5r2Rt4KQxapIMdhbk+4B0Hl9+PcHI",
	"ZPwsvrNfkPKswqSZQoHLMglGGRIBk2ZkReL4Aeb69QQjgR8LnASyTPp768YEffJF63qh7zLIKHjs3lwO",
	"SAOA9xLLxXlgguHZPJlTOCXkXnKpHxGfs5LiJSDD8p8PgswVoUB+zAI5I3Ei5jCTZpC6grQNpJUQXNVH",
	"R/TVvxFcqLxerNy7qd8ub2nvEBxHcAnBUfyhqOrrM1ulGQQntu+N6eszCM4g+AzBG0gd1x++0adKqAht",
	"Y67opaXq3UUEFxCcRHCZXPkYqfNIG0XaQwQn9KkVBN8jdSJ0nAn8dHUME0l/heV+NicDBFfwqComrcbV",
	"PkHIAZbHLOEUkKdiMD+EKQ1m4BkF5PGdxlisJLFD9WlPglEEhc315oUCr9hkyvEKGABSiHpRIp33JxwC",
	"DBI7odojevYqy+XYPmotLsFrj5A2jrSnmMVwonr7vT63SKUVLnjHjeodfezW9uw80YMHhmzUG/qTV0i9",
	"pZduErnGFVU83nJ5dgB8J+V8jCXB5AFfOLMrg0swPxZYXuGUIccoHK/0dNeGsURZr16IIscP1K+Q39Ib",
	"/fSywHPKOYnLgFj0+uGJwTSDJTYO23hhf07Cple2OV20qaJJb30aWUKahrS7SHuN1Bd1KqXz3iC9nFvU",
	"11fq1MuMMaeYMo6pxo3QVIP1MYfZlaJYOlJ7pqUv/prhi1QSYBVwFo/FiwUfX+XQiGEGXGPzItYVRp+/",
	"h2CZeIRl428Rbq49x19i2T83/sJVBB8g+Ev1xgbxOAsIzlLB5tlr/wf4AWWQSXelUqkEk+d464sgnAnH",
	"zerdt7p2GxXV/z33xWlUhOe+xn//AfrOYc9Xfq9/mMOPJ6r1A1+ZK+rzC0ibRuoj4gFXkPoH/qCuI1ju",
	"Sp09SS5jEjXh9HE8Kw2F6USNQ/Z5e6YbOVtLrF4xMHr5/dbLR5i1Dp+x4jI600KXPYa8eubU5lpx69kC",
	"KqrVpfXtkUm9NINUVb9dprKxsDAaQe3oR1TvxwI4Q29XpAJw67nFn2OYCR6tz3M8ly/kmXQq0gIMZbez",
	"xqn6VGGC1Z5EpL2imOMyEfEthRCXEAjUVe++3loZJxzF8Dc6sq0tVn+9QTCsTDyR3MllEVzUpyY214oe",
	"hQpiqwSucuCnCwqrFORYkfV5+w3YCxb68pyigGyv4pBjllVAh8IR1sUIbR10OEeNYGycvCFDLq+DxESI",
	"KIgxvEbaFNI2KuP39fcjYWK5xFn07UxCefbad7IPSDLGs7VlYm1lBFcp0Gy++4Dd5v3fKtMvUFHlC7mc",
	"PXyu3nikl/7cnp2iFuixDHw99dPYrPwCn2ZnYeQSVypW40vCJt1gVTHikgDv4wOqGiRh7roTUXuiAdUf",
	"hbr8UYi9RlEIO6bUTlCp9jS/uX8hSYIUbBZ5IMuGrwuXgHmh3zNOA8XMgeXgR2VZhY0d/Fo5tU/USzIk",
	"v3T2MdJ+J671FbYHuFr963Zl+kV0gEMHTFAKAyaIAxf55BDFm1MNmiUetI4Z2sDH8sSxJ0kIM4cOmOR5",
	"Qcg3SoJ4rHqkp9GE/2GD5eb2vI2annvcusVoufNGCtCGuQ2dKB1yZ6pq+MkGz9RA84abZEi2HTFVd+Db",
	"yNn+PydzfTka7TRUsHXMc/veq61nC1akb+bfjZvnl4DNKYMhIZyQz3PKl6w86CWuuriha5MkKVwlCdYj",
	"4rvXcNgzoiG4SAqQTxB8cJpTjnxORjpy4cteJmHz+Kmu7p6jx47/z4nP2L5MFvQH/d8vRssCMScMmQGm",
	"G9tuIm0Gp6jqPILTpADxoDLztDKrftwoVZ4/qT5ep/Ei0n4hQDjmugzBhwhOoCI0Ekm4gFS1Mv1CL41W",
	"F8f19WcIrm4tz+t/rZIsuIzgrx83xhyT6051H+9Inejo/uzbru50z9H0seP/tAd/oaGwbGUHtQGFKzGK",
	"50YwbxOdg1V+anAWhCg4J4s5dujroKoIyLNczhFe0m92XqsRuYxSkMyiY0BkbEumjMAY8DiGw2ETAc4E",
	"w2bzHG+bb1iga9Jsn62DkpBmBAkpGpH9uMoxO+VfaMk2sLolC7nsNwV7Ad1WlKun6lpf4SvBFMQsu+tM",
	"tpaoxCscUJGac7YTEZXZkCArMJcJJzWwlUQdg7d8a4b4DQniMzlBDuVzpKntq4LuumgiGZKL2/Mz7nDr",
	"kk1/XPWTmrhszA4Utz2S3WPJH0q5NawKtjNh2x9uF32gvI2A3ivqTEYo8EpMdI1yx5cFjq/P6+zQ3TZ/",
	"NUCNUVY5ypptiOeOEMh5V/ggK2x/P6kS8Sz2UBd9eOBVU9sAIuCz+LoEw4qiJFwFtNKKHw2yvsMFtu92",
	"XEHdeZPrkIUBdse/E2//Hbmy3UJrt9AORgstQIG9zbAadh2ixlhkjyvYxJvXqghF2P3qY9TI8rII0wwy",
	"BYlThi5g3gNzESH2xheALBvYx2H9yAjCFQ6YAJxmODlzqR/IlwznfUk2rq8Zhsh9BUiUeroA5NjjDeCL",
	"g0fDRHN8v0C4zCk549aOfiAf6T13hkkwV4FEH8SkOrs6U5gAQQQ8K3JMmunpTHX24DCCVQbJbJOOgHwA",
	"EPFhDSHmhF2ioyVD9I6aFbmhO5Wi5TReAXSRGlszxuRlmU6YanaU3vu2fsiEQ5szFM/wNI81kBhnr8uX",
	"ij9Ik4HUo9VFpC0hbYPqVCGfx74igFKk3tFv39Pfz1CHRG5JDpJ6ZZgIaEVzL/nvqpn6zPmbr/C3mF6K",
	"GkG0ngV7SaetqOcnF+05Wbk1TxhOa7iPcZyiPiP9gxLWlKOpruZpSmVu2U4Ugu9JgFBG6lvsnNW/kLZA",
	"vp+o3nik3/q7lVTZgEcm/b0XGL+/eP2iQ9ujOO+r+Tg7DcUe0kjcY9xxNiv9ZDg9q6/OtzDUOFc3Ltvp",
	"9WU7iWU6bESHysDT+dxjeQR3Wn3YY4/cahLaTxOnz+9p3vOrq4+qU6NbxZHK4tL27BRZ6L6M4I2DCiVe",
	"kXqUOMGIguyjrf6L5BgaJgJZOSlkh1z8yBdyCieykpLEoWiH2fmsseSgZcYm+1o0J9ZfjtefFpvFUmvI",
	"46ljjkGORY3hnyoEV0f9MgbHGEaW6wLCxsFOxHrPCChE6p3Nd3OV0hRdvE4xqZlQgI2gjEFA/RtpJf3d",
	"Y33jNoITm2uTledPWgKiu3qaiYyPSSmG9O4xRNb68oahwgnSjp/ERgn/ZYDc0a5jzaPRBAVzMxbxIZQ6",
	"Kj5CUXd3Eykaearfuq8X562o2WSWtc3MplCt4OowFc30/JQdxMRIrklXqkxsrhUrsyotXXk3z+3UIyO4",
	"SjHFAzFhkWWSlqo66BKO5LCxkjl7nfjWgo8Tjy7ukRqGxOaBAiSZzIBUVUSW5MhGTcV8EONG7YSN/VFd",
	"m4thoUO4ZF3bTRtaA4wo/8XxVI0zljqKsVFeC67q5aXKg7dEpUeJPn/An9U7lftvKvdetL1ZqyccR1NH",
	"m+ggHLozoT//tz63SHSkRs5nTZSLoaM1qPXXZkhWE86PVe6/OWJ2U490/FBIpXpA7QsywtJhSOJimLXb",
	"g9h2uiSHa//BfiPJko3+BGJ9k0DfgwBiuQzHg3bvN/YoMwg/6CDQTMzGoXO7Ec6sZxD8WR95SuPRNrj6",
	"gGsTMc3cBuZGM1SEjt1YmEG3CPqubMO79jMUmo57JGdZwLGmn6KRn1SDroMLZbHMxwFioUVVx0L8PS6o",
	"+i/699O9sQ9by5OVtRKCHzBoGxNfREW4dXNZL40iOGFCOtkTTy5o5cL4yCIxi9XdzCy4hO5OZwI7qIZP",
	"JxI4OXTmVJMTmD1SLWPjR5DDqWgj+sOXLelPmh6j+uK5VdZwaucC2XfRahV8y6b8TSmWjSQzrKRE95rI",
	"EUSHwkLITEIjMvN4oraZHDIzsURs+pearF3G8nGjRBYJHfGuCTCySGu//dK6/TyrrQ93ye1jQeZmy6KC",
	"0yXf8w8OYIVtt4cbVOdgdZrukYs82MBalNa1Z4ccuCt+/vu09q0n1YjMs92hap2aHi3lba5Nbv35+uNG",
	"ydyL/BvSJo22gvbETOYwJhHUaRUfAcdREQYnn+XDsB4iyojCwi66eTQ68DI2/B+O2CvoFIO4MGVfTdTG",
	"pf0qh8WJCz8ty6+nKGFafnLYXKluVCqyIAcU4EWC8yAvXAX2nX1Nw4KE79A1uhsMNEcDD+Bw6ZHzGMg2",
	"HrRUnGIV74x+k9mZtFs/jg2MrVO+l6lmEtWK0OYk/FPBOJvRmQs+YwQu1hE+vXzWeGwzS61NBrAG13HN",
	"k5liRkdtHDwAcdGnCx6xQiO+IIdvZLKf1HdokqKAAwgjDd/YcNzCaVG7XN2AcrVX1nXuviAHR7VG+Thy",
	"b0d0sbN2SEKTa630SM+YRtkuph6AYqqP+w2oZByMsuvHjVJlbpminG1NRdmlmNXZt9sTr+yrIs1JtHdg",
	"tHdgtHdg7CDQ9aJ+ZKCbHMb/RJX/TpHvseux59LEB+57Im3Q3+wyoP9bitoetu1hW8bDmorp8LD2Sbve",
	"0+WzT+LgJ/9edljJSvAms0OOdHuSF7kPj2vybrN686L2xrE2arckant3i9WN2u0Mqp1BtTOo3UULATsQ",
	"HRmU/ZWbQd0Cz3tEDk3DIPgNKeFu2HH6aHs1VQs74JXKWFF/+ZsLN1t1TcRB6KvsEJl8TKbO7ot56vZB",
	"WL8f3X1xnF/b5AaM9QKn+CDXbsO0040WSjfcuhnYiTlMqBmzKG6GdMlh41O80rgBCvaakYlR+142qk2k",
	"qTXysJemtxGwjYCthIAxKuWudyYcwmJ5EFOMvajVN1MIPkXwZ6SOkfKOcayI63WxnnFUc5xpehKGoSEh",
	"1fdPBUwbHx37vN2hyWX4nUXH7WJ82ze0qm+IUY//9HyDqzpKRpaumpDsffkCpmMFaSvb98ars+vVOy/0",
	"xxqTYApSjkkzg4oippPJnJBhc4OCrKRPpE6kGAzAbsv4vTq97HOznE4mWZHr7AdyJ/cTK7NXuE4203lZ",
	"ZK5fvP6fAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
