// Package routers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package routers

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponseRole.
const (
	MeResponseRoleAdmin  MeResponseRole = "admin"
	MeResponseRoleMember MeResponseRole = "member"
)

// Valid indicates whether the value is a known member of the MeResponseRole enum.
func (e MeResponseRole) Valid() bool {
	switch e {
	case MeResponseRoleAdmin:
		return true
	case MeResponseRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for StoreMemberRole.
const (
	StoreMemberRoleManager StoreMemberRole = "manager"
	StoreMemberRoleMember  StoreMemberRole = "member"
)

// Valid indicates whether the value is a known member of the StoreMemberRole enum.
func (e StoreMemberRole) Valid() bool {
	switch e {
	case StoreMemberRoleManager:
		return true
	case StoreMemberRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for StoreReviewStatus.
const (
	Approved StoreReviewStatus = "approved"
	Pending  StoreReviewStatus = "pending"
	Rejected StoreReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the StoreReviewStatus enum.
func (e StoreReviewStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// AcceptStoreInvitationResponse defines model for AcceptStoreInvitationResponse.
type AcceptStoreInvitationResponse struct {
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// CreateStoreApplicationResponse defines model for CreateStoreApplicationResponse.
type CreateStoreApplicationResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// CreateStoreInvitationResponse defines model for CreateStoreInvitationResponse.
type CreateStoreInvitationResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id 店舗メンバー招待のID。内部的にはstore_invitations.idと同一。
	Id openapi_types.UUID `json:"id"`

	// MaxUses 招待リンクの最大使用回数。nullの場合は無制限。
	MaxUses *int32             `json:"maxUses"`
	Role    StoreMemberRole    `json:"role"`
	StoreId openapi_types.UUID `json:"storeId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMenusByStoreIDResponse defines model for GetMenusByStoreIDResponse.
type GetMenusByStoreIDResponse struct {
	Data []Menu `json:"data"`

	// Total 店舗メニューの総数
	Total int `json:"total"`
}

// GetStoreApplicationsResponse defines model for GetStoreApplicationsResponse.
type GetStoreApplicationsResponse struct {
	Data []StoreApplication `json:"data"`

	// Total 店舗申請の総数
	Total int `json:"total"`
}

// GetStoreMembersResponse defines model for GetStoreMembersResponse.
type GetStoreMembersResponse struct {
	Data []StoreMember `json:"data"`

	// Total 店舗メンバーの総数
	Total int `json:"total"`
}

// GetVisibleStoresResponse defines model for GetVisibleStoresResponse.
type GetVisibleStoresResponse struct {
	Data []Store `json:"data"`

	// Total 閲覧可能な店舗の総数
	Total int `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	PictureUrl  *string             `json:"pictureUrl"`
	Role        MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Menu defines model for Menu.
type Menu struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    string             `json:"imageUrl"`
	Name        string             `json:"name"`
	SoldOut     bool               `json:"soldOut"`
	StoreId     openapi_types.UUID `json:"storeId"`
	UnitPrice   float32            `json:"unitPrice"`
}

// Store defines model for Store.
type Store struct {
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
}

// StoreApplication defines model for StoreApplication.
type StoreApplication struct {
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	ImageUrl     string             `json:"imageUrl"`
	Name         string             `json:"name"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	Room         string             `json:"room"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// StoreMember defines model for StoreMember.
type StoreMember struct {
	AccountId   openapi_types.UUID `json:"accountId"`
	DisplayName string             `json:"displayName"`
	JoinedAt    time.Time          `json:"joinedAt"`
	PictureUrl  *string            `json:"pictureUrl"`
	Role        StoreMemberRole    `json:"role"`
	StoreId     openapi_types.UUID `json:"storeId"`
}

// StoreMemberRole defines model for StoreMemberRole.
type StoreMemberRole string

// StoreReviewStatus defines model for StoreReviewStatus.
type StoreReviewStatus string

// UpdateStoreApplicationReviewStatusResponse defines model for UpdateStoreApplicationReviewStatusResponse.
type UpdateStoreApplicationReviewStatusResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
}

// CreateStoreApplicationMultipartBody defines parameters for CreateStoreApplication.
type CreateStoreApplicationMultipartBody struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image 店舗画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き屋
	Name string `json:"name"`

	// Room Example: 605
	Room string `json:"room"`
}

// UpdateStoreApplicationReviewStatusJSONBody defines parameters for UpdateStoreApplicationReviewStatus.
type UpdateStoreApplicationReviewStatusJSONBody struct {
	ReviewStatus StoreReviewStatus `json:"reviewStatus"`
}

// CreateStoreInvitationJSONBody defines parameters for CreateStoreInvitation.
type CreateStoreInvitationJSONBody struct {
	// MaxUses 招待リンクの最大使用回数。省略時は無制限。
	MaxUses *int32          `json:"maxUses,omitempty"`
	Role    StoreMemberRole `json:"role"`
}

// CreateStoreApplicationMultipartRequestBody defines body for CreateStoreApplication for multipart/form-data ContentType.
type CreateStoreApplicationMultipartRequestBody CreateStoreApplicationMultipartBody

// UpdateStoreApplicationReviewStatusJSONRequestBody defines body for UpdateStoreApplicationReviewStatus for application/json ContentType.
type UpdateStoreApplicationReviewStatusJSONRequestBody UpdateStoreApplicationReviewStatusJSONBody

// CreateStoreInvitationJSONRequestBody defines body for CreateStoreInvitation for application/json ContentType.
type CreateStoreInvitationJSONRequestBody CreateStoreInvitationJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(c *gin.Context)
	// GetMe ログイン中のアカウントを取得する
	// (GET /me)
	GetMe(c *gin.Context)
	// GetStoreApplications 店舗申請一覧を取得する
	// (GET /store-applications)
	GetStoreApplications(c *gin.Context)
	// CreateStoreApplication 店舗の作成申請を作成する
	// (POST /store-applications)
	CreateStoreApplication(c *gin.Context)
	// UpdateStoreApplicationReviewStatus 店舗申請の審査ステータスを更新する
	// (PUT /store-applications/review-status/{store_id})
	UpdateStoreApplicationReviewStatus(c *gin.Context, storeId openapi_types.UUID)
	// AcceptStoreInvitation 店舗のメンバー招待を受け入れる
	// (POST /store-invitations/{invitation_id}/accept)
	AcceptStoreInvitation(c *gin.Context, invitationId openapi_types.UUID)
	// GetVisibleStores 全ての承認済みの店舗と、自分が申請した店舗一覧を取得する
	// (GET /stores)
	GetVisibleStores(c *gin.Context)
	// GetApprovedStoreByID 承認済みの店舗を取得する
	// (GET /stores/{store_id})
	GetApprovedStoreByID(c *gin.Context, storeId openapi_types.UUID)
	// CreateStoreInvitation 店舗のメンバー招待を作成する
	// (POST /stores/{store_id}/invitations)
	CreateStoreInvitation(c *gin.Context, storeId openapi_types.UUID)
	// GetStoreMembers 店舗のメンバー一覧を取得する
	// (GET /stores/{store_id}/members)
	GetStoreMembers(c *gin.Context, storeId openapi_types.UUID)
	// GetMenusByStoreID 店舗のメニュー一覧を取得する
	// (GET /stores/{store_id}/menus)
	GetMenusByStoreID(c *gin.Context, storeId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetStoreApplications operation middleware
func (siw *ServerInterfaceWrapper) GetStoreApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreApplications(c)
}

// CreateStoreApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreApplication(c)
}

// UpdateStoreApplicationReviewStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateStoreApplicationReviewStatus(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStoreApplicationReviewStatus(c, storeId)
}

// AcceptStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "invitation_id" -------------
	var invitationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", c.Param("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invitation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptStoreInvitation(c, invitationId)
}

// GetVisibleStores operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleStores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVisibleStores(c)
}

// GetApprovedStoreByID operation middleware
func (siw *ServerInterfaceWrapper) GetApprovedStoreByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApprovedStoreByID(c, storeId)
}

// CreateStoreInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreInvitation(c, storeId)
}

// GetStoreMembers operation middleware
func (siw *ServerInterfaceWrapper) GetStoreMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStoreMembers(c, storeId)
}

// GetMenusByStoreID operation middleware
func (siw *ServerInterfaceWrapper) GetMenusByStoreID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMenusByStoreID(c, storeId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/store-applications", wrapper.GetStoreApplications)
	router.POST(options.BaseURL+"/store-applications", wrapper.CreateStoreApplication)
	router.PUT(options.BaseURL+"/store-applications/review-status/:store_id", wrapper.UpdateStoreApplicationReviewStatus)
	router.GET(options.BaseURL+"/stores", wrapper.GetVisibleStores)
	router.GET(options.BaseURL+"/stores/:store_id", wrapper.GetApprovedStoreByID)
	router.GET(options.BaseURL+"/stores/:store_id/members", wrapper.GetStoreMembers)
	router.GET(options.BaseURL+"/stores/:store_id/menus", wrapper.GetMenusByStoreID)
	router.POST(options.BaseURL+"/stores/:store_id/invitations", wrapper.CreateStoreInvitation)
	router.POST(options.BaseURL+"/store-invitations/:invitation_id/accept", wrapper.AcceptStoreInvitation)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtvUxNJGv8qW333ciBB9Gov7/Tc2vP23LW0vHvhUlaTNNCa+XMzPa6Ular0DHhR4OQ8keOk1tVFQVgT",
	"9/R2UVE+TDMJvNqvcNU9k2QmmckECDGyvKFg0vP08/f3/OHJDZBWZU1VkEIMkLoBjPQYkqH49WQ6jTRy",
	"gag6OqNcwwQSrCrnkaGpioH4AU1XNaQTjMRxXc2Kp7/V0QhIgd8k6oQTHtWEIHYWycNIP8+P5yRgCPoZ",
	"/uaIqsuQgBQwTZwBEiDjGgIpYBAdK6Mgl5OAjv5mYh1lQOpS7UXJvXmodl4dvoLShNP+g44gQeLSk5qW",
	"xekYEbBgI4OMtI41fhSkgPNmfrswX7n3cnttitHimdMsbzk3J3fslcp/JhhdY7QkODH6cYbRFWd2ems9",
	"z/LW1wqQ4iTiAl3D6JsLBBLTaEt55/0vcPWZwzImBGVOkoAKM5CgPoJlFKtHwViAjyDVGMW24xppcXwX",
	"LEotTMHsR8x+yexZZm+Upx447ydbmeUyrvG3NwvJ8PpFwxUjyI13t73KubFKjBbLi3lnaXnr3Wbl3orz",
	"4Nvy3AuWtxQzm2W06Hz3ypktMFqqTDxyCj/tLMyyvOW/Hytk8BiQAD8Ph3koEd1ENYawQtAo0oXPdDnQ",
	"xJGGaKvrRfJZN8xVPtN1VY92DRkZBhwVH7Tmonow7I7PETmLFNM4Ne665Ono+zKQQBHqBMmxEceJcvre",
	"hVDX4bj4WyUw29I/p5j9hNkbjBYrP98pz70AzYZskE8wViUdIWQjkhkdkrOR7q5lrsFjx6V1fbijgrok",
	"92ZXD3c6LOlfsIGHsy6edlTUXQi5c/+/20+XnTulbfsdo6uezB2U848IZslYtHRGLQmi61DWsuLtq22U",
	"AeK1sBvPoha6xIaWheNfQjkMeySAZIizAax0n0SmqthEouE0MXV0URdkI2DeVxl4KI8UU3bxT3itBGBG",
	"xopP3laoXeXZL22AkxbFkwC/Zr35nebGnpWBZThaVUXTh0qUUQw1m/nKJL7PhlU1i6Cyu/wmAVPB5JyO",
	"0yhweiSrQlI/rpguTrROh4qrU79e/PR9otb5D1O3G6+9pe99V6e6qsrxqR379CjeaFSnT4UBliL16M9l",
	"vw6VdqwT2Isd4hsGf+JtMghMp1VTIW3GbhxyX1GxsrteY4/I3P1Gt66oWhlek7YFyMcY5HxUppGhAnmq",
	"HwpRQrNv+ihoSMnwcxKAmqar15DbYvK7USaU3EUtE9qp1+kfoq49tgFvNhj3H5Q2dUzGL3DCqDqh4f5w",
	"ARmGB2aYC59W1asYVWM5BbCRvjyCjMue+1w2vPP12lDDX6BxkOPXYGVEFXGFSdZ7uW8EGZ+cPHcGSOAa",
	"0t2rQLJ/oD/JlaFqSIEaBikw2J/sH+SuB8mY4C8xJmo+/usoEgHJ7SZMywOBl75uVSgU4NpXvHgsmRRz",
	"A1UhSBEvwrpXJK4YrrCuiuMM0FB3CiGDzvLVF/xpTgIJF1KieD2LDpJPX7UawiOznzPrBbOWmP1ya/05",
	"o0VmPWbWGrOeiq6kwE1xPDnQMXaCfXsIR+XFVT9TjL5n9CGjJWa9ZbbNrJ+ZvSyeT1cmHjm3X3MGT3RQ",
	"X7EMMut/vFVzGzZrhdnPmL0RCCWQutQcRJeGckM8ocky1Mfb0Tyz7jp37jvv5xldYNaUuCEh0KXPJ53R",
	"yrOaGvuDdLSWg4QQPfqxdGs9v/10+UP7mnv/YPfurxQfVWZvbucnyyvPdhZmGZ1mdJXRiY/Vp5tN2uTE",
	"EtBUI8Rbw2fqwE1pyCCn1Mx4gz5kM0uwBnWS4Jm1rzrGqKukZX1enwY4S/cFvqwxe9X7maciJEs8DO3n",
	"3k9aFEj0r8rEBqMzjC5zmcS0VYbX/4yUUZ6SBpLJpARkrNQeRNX40dXFW8e+w/LWn8599jnL03Nf8p9/",
	"RcPnGF1zSu+dzUVXmaKucIfDzJ5j1iPhxWvcltYSs94wWhpInj3VVH4MY4WbS4puL+q68Uvs/DjVJGus",
	"qNW+okbyd8kTASIn4mg0lDWxjURYmROgwevvXBMQdg52Yv49FAOFzLq79W6xXJhldJ7Rhy4mdRMKeBCU",
	"OAhYr5ldcN49djbuMDq9tT5Tfv59T0D0wGA3kfExLzvseYEDG8y+xegcs6YZfegFKp3mAcgBYYHRf3gg",
	"d3zgRPd4rILCPKNPGZ1wc4jLnWs+wdGxY13kaPKJc/uBk1+qlW9VZRWdm5NO8XXAoXoh1XEuupn5XXWI",
	"EGP2D4KXdaGUfHnBcptJp/Cscm9F5JmZal2wt4zMaNHFlCaIaVVZJtzmsc8dhSdueP/4zOREbjVDknh8",
	"uy3aOB3KiCDdEBKI1pK3dvXGsnoRaERtyaf+uGHHUKvSobVlGxYQOtqVxzXkbWSqzgXLLsYjcVmLFp3S",
	"s/LDt8Klbwp/3uS/W3fLD16V7784yma93nAcTx7vYoII+M608/zfzuKK8JE6O7/vol08H61Dbbg303Xu",
	"6Eu3yg9efVKdQX7S97WZTA6i+gNB4dlhaOLaCOvGDOJbjEncqP/B80YCitUvAbGhTWDoalhbKSNw0f7z",
	"xgF1Bq1X3yLDhHeezdtJvLOeZ/SfzuQTtx49AtcQcO0iplW3xhrRjOVpYHmLK+i2QN+1HXqvXrZ7nUM3",
	"cU/0LMu81gxzNPGR5fH18UJZW+ETALGWQ9XAVs0BD1TDN3jCfO/W5vbqTHm9wOgmB21P8BWWp9t/X3UK",
	"NxmdrkI6L8TcA/Wxa69Yt266yRURFsX9SBY9Qm9sZ6KMfdLL6cICp8bPnO5yA3NAruVtcUUlnLI96Xz3",
	"Y0/mk67XqKF4XhtrBL1zmdFS703wazEVHkptxUjCV9ZF12+h+9sfYcu/3+XsyiKtzD0pL1htLGbLWMGy",
	"KYvJ9wEtaTeOIMJX8z7YkLwTpfDRyLx3hgzubGFrfWb7p5e/bBSqa87fMnvGm3Pa31erS46Vv2zc6h1s",
	"p1MsT6Or4dJh+AdtXBC1ygPuFlf81oG3YH84yqWobw20C1P+9YYjXPpQ/Xk79dyvK/J30yUlZKSYRus9",
	"Nv93pQ5N5Ed8BSw29r3vavVw7B/1UvuYT0TbujmeRLDq16qB0LyCye9ZY/bazv2pysKbyt0XzmMbSMDU",
	"syAFxgjRUolEVk3D7JhqkNSnyU+TICc1NSeLP1TmVkNeNlKJBNRw/wgy+vE30IBXcT9M91/RQG4o9/8A",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
