// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponseRole.
const (
	Admin  MeResponseRole = "admin"
	Member MeResponseRole = "member"
)

// Valid indicates whether the value is a known member of the MeResponseRole enum.
func (e MeResponseRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Defines values for StoreReviewStatus.
const (
	Approved StoreReviewStatus = "approved"
	Pending  StoreReviewStatus = "pending"
	Rejected StoreReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the StoreReviewStatus enum.
func (e StoreReviewStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// CreateStoreApplicationResponse defines model for CreateStoreApplicationResponse.
type CreateStoreApplicationResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetApprovedStoresResponse defines model for GetApprovedStoresResponse.
type GetApprovedStoresResponse struct {
	Data []Store `json:"data"`

	// Total 承認済みの店舗の総数
	Total int `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	PictureUrl  *string             `json:"pictureUrl"`
	Role        MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Store defines model for Store.
type Store struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    string             `json:"imageUrl"`
	Name        string             `json:"name"`
	Room        string             `json:"room"`
}

// StoreReviewStatus defines model for StoreReviewStatus.
type StoreReviewStatus string

// UpdateStoreApplicationReviewStatusResponse defines model for UpdateStoreApplicationReviewStatusResponse.
type UpdateStoreApplicationReviewStatusResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
}

// CreateStoreApplicationMultipartBody defines parameters for CreateStoreApplication.
type CreateStoreApplicationMultipartBody struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image 店舗画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き屋
	Name string `json:"name"`

	// Room Example: 605
	Room string `json:"room"`
}

// UpdateStoreApplicationReviewStatusJSONBody defines parameters for UpdateStoreApplicationReviewStatus.
type UpdateStoreApplicationReviewStatusJSONBody struct {
	ReviewStatus StoreReviewStatus `json:"reviewStatus"`
}

// CreateStoreApplicationMultipartRequestBody defines body for CreateStoreApplication for multipart/form-data ContentType.
type CreateStoreApplicationMultipartRequestBody CreateStoreApplicationMultipartBody

// UpdateStoreApplicationReviewStatusJSONRequestBody defines body for UpdateStoreApplicationReviewStatus for application/json ContentType.
type UpdateStoreApplicationReviewStatusJSONRequestBody UpdateStoreApplicationReviewStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(c *gin.Context)
	// GetMe ログイン中のアカウントを取得する
	// (GET /me)
	GetMe(c *gin.Context)
	// CreateStoreApplication 店舗の作成申請を作成する
	// (POST /store-applications)
	CreateStoreApplication(c *gin.Context)
	// UpdateStoreApplicationReviewStatus 店舗申請の審査ステータスを更新する
	// (PUT /store-applications/review-status/{store_id})
	UpdateStoreApplicationReviewStatus(c *gin.Context, storeId openapi_types.UUID)
	// GetApprovedStores 承認済みの店舗一覧を取得する
	// (GET /stores)
	GetApprovedStores(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// CreateStoreApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreApplication(c)
}

// UpdateStoreApplicationReviewStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateStoreApplicationReviewStatus(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "store_id" -------------
	var storeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "store_id", c.Param("store_id"), &storeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter store_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStoreApplicationReviewStatus(c, storeId)
}

// GetApprovedStores operation middleware
func (siw *ServerInterfaceWrapper) GetApprovedStores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApprovedStores(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/store-applications", wrapper.CreateStoreApplication)
	router.PUT(options.BaseURL+"/store-applications/review-status/:store_id", wrapper.UpdateStoreApplicationReviewStatus)
	router.GET(options.BaseURL+"/stores", wrapper.GetApprovedStores)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fn/TxRHFP9XzLQ/LneHSGPvN2yNtVZLJKY/KCHD7QCjt1+6O4cScsnNLhAUKIQKlEpCpFS+nBw02oiK",
	"8sc89g7/i2Zm79tye3fa4NU2/WVd92bmfd77vPd5M8MoShiaaehEZzaKjyI7MUQ0LF+/sghmpIcZFuky",
	"zSRNYEYN/TqxTUO3iRhhWoZJLEaJHE9V8VSJnbCoKYaiOPJeLR1PLhUePjvOTgHPXf4aMo43Mf7O3Sz8",
	"OgY8C3zXFgbsCFWBb3pz00f7Gcg4t3SkoAHD0jBDcZRKURUpiI2YBMWRzSyqD6K0giwyTMndHoZZSiL4",
	"3CIDKI4+i1Z8ihYdiko/rldPSCvITvVrlDGidjExv2xQxYy0MaqRWqvS7I8pahEVxW8iCSyAI7hqb3kB",
	"o/82STBh9aJlGVb9OGrEtvGg/KGx7dLAMBuXCOsyTcsYJqr03K5vT8UMS/4Y0d4vjMJA0SK2LDwi/28w",
	"nKxNgPz9w+Ptmfz+JPBD4Dk/H4DnCi9m8wt7lfBSnZFBYtX4KMGVVg9z9BuCk2yovnd2OTvIPayZSTn7",
	"TlNei9PCLF4lDWJJbTOJR65hLYw/BREN02Qg1fwvIcntl1PTGjBpgqUscsOSy+qpZBL3CyeZlSJhJWMk",
	"JTKipzQ/h7R+YiEFYVWjepW/jfK9hLna2wCSop2w6PkJVBu46qwZ/dvRoBoeLMWi5ke9HiuWYWjNy01a",
	"1H1f5QwlgLrKeF2/r58QrBILJtFVYVJBuFi0UlXEXKKGkKKgG6YaKs6V9f9DQt1Uc2sDLsSdJFIWZSM9",
	"YmHf865EwkjprIfYdjHRqHA+YRh3KCmxG0fUTvQNELsP+8P77OL4iuqZ9AoZQWlhhuoDhkweypLFyW0D",
	"xD7T1X0ZKWiYWL4pFIu0R2IiGIZJdGxSFEcdkVikQ1QOZkMSX3RIqpl4HSSyJQneJLWXVRQXqu7rnQyA",
	"z6+ceDYWE/8kDJ0RXU7ElayI3rZ9Z/0QNyPghKJKJ4PJ8v0V8TWtoKhfUPWwXiUfE2eVDodgBHcHnD1w",
	"1sF9drS/AzwHzho4WXCegPsM3ElBxblY+6nBCXb1EET5le1qUMDfAl8FvgvOa3BdcF6AuyG/TxfGHnsP",
	"XgqAnacYr6YAwfkT3ANw58TT2QR3C9yDQCmh+M3aIrrZm+4Vmx5Nw9bI+0QenHlvdtF7uwR8GZwpaSEq",
	"1aWtyjuZL6Zhh6RW+M4U+SpBbHbBUEdOhE1LJRk1scWiQqzaSnueSuQatqPK1sFbX5SUZcHdLj4zXHq5",
	"Kzxzd4pPnpPk/lwYOwA+A3xD+JpxkII0fO87og+KKm+PxWIK0qhe/lCvpdUX7NeeOwsZ59vui5cgw7uv",
	"iecPpL8beNbbfesdrvhBllKdX8l46xvgLoDzWPKTFZQ76+C8Ar7bHrt6oUbR+6kuWFXqd9NKbKo99v6Y",
	"qvG1qaulPlxe8otYZ2CRzmZrnOgUTbt1WOcIrCG2UekaETs91WhyyAqp0kCnduaP3qzkJ+eALwFf9SWt",
	"lYohimBXaIXzEtxJ782adzALfPpofya/89s/rbDSfntHKwV0TSi5uyR14ADc+8AXwJkGvlosVD4tClAI",
	"wjLwn6T4CYydrcNYEoUl4E+AjwHfBj7mo/Ppk4jOnm0hovHfvQePvMx6uSOWgpXzJsa93MtAQn0KHVGg",
	"aGFaFcMhSwzcpxLLvgxKJr/s+Ptzb3Kr8HBT9pkZn9MPb9zlw7mvKTUS06hZR/39eJt/bo6OyhF9VE3L",
	"3poKaeLNTzByZ2xhjTBi2dIDuVsXu+XKXr1kCJ1UbaUq/E0OKCIM9bcOjZkN7htO96DT7IzzHp3q9Irl",
	"A06czboWz3m7W/nV1zKlJ2Q+H4p3Zz7/6Hl+ce//blavm7VUdnKPC3MTx5nx/ObWu+U54NMlYRFAzrWw",
	"QQRyZ9rb+cVb2ZQ5UoHzZQt5KeZoRWrDs5nvi0Rfv59/9PxM6VrnTNutVCzWQSof5Apb/9az3geW9YkO",
	"Yje6PAheX3/Mi4T6d+Vh7IddaB/tZ46fbHxKJJYZaoC39hwu6beGS+229kZF2MmCm323OFVYflWY3/PW",
	"XKSglJVEcTTEmBmPRpNGAieHDJvFz8fOx1BaqfmbwMrTwsJ2yGQ7Ho1ik0YGiB2hd7GN79AITkRumyjd",
	"m/4rAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
