// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponseRole.
const (
	Admin  MeResponseRole = "admin"
	Member MeResponseRole = "member"
)

// Valid indicates whether the value is a known member of the MeResponseRole enum.
func (e MeResponseRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Defines values for StoreReviewStatus.
const (
	Approved StoreReviewStatus = "approved"
	Pending  StoreReviewStatus = "pending"
	Rejected StoreReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the StoreReviewStatus enum.
func (e StoreReviewStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// CreateStoreApplicationResponse defines model for CreateStoreApplicationResponse.
type CreateStoreApplicationResponse struct {
	// Id 店舗申請のID。内部的にはstores.idと同一。
	Id           openapi_types.UUID `json:"id"`
	ReviewStatus StoreReviewStatus  `json:"reviewStatus"`
	SubmittedAt  time.Time          `json:"submittedAt"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetApprovedStoresResponse defines model for GetApprovedStoresResponse.
type GetApprovedStoresResponse struct {
	Data []Store `json:"data"`

	// Total 承認済みの店舗の総数
	Total int `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	PictureUrl  *string             `json:"pictureUrl"`
	Role        MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Store defines model for Store.
type Store struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    string             `json:"imageUrl"`
	Name        string             `json:"name"`
	Room        string             `json:"room"`
}

// StoreReviewStatus defines model for StoreReviewStatus.
type StoreReviewStatus string

// CreateStoreApplicationMultipartBody defines parameters for CreateStoreApplication.
type CreateStoreApplicationMultipartBody struct {
	// Description Example: 外はカリカリ、中はトロトロのたこ焼きです。
	Description string `json:"description"`

	// Image 店舗画像。JPEG、PNG、WebPに対応する。
	// 最大ファイルサイズは10MB。
	Image openapi_types.File `json:"image"`

	// Name Example: たこ焼き屋
	Name string `json:"name"`

	// Room Example: 605
	Room string `json:"room"`
}

// CreateStoreApplicationMultipartRequestBody defines body for CreateStoreApplication for multipart/form-data ContentType.
type CreateStoreApplicationMultipartRequestBody CreateStoreApplicationMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(c *gin.Context)
	// GetMe ログイン中のアカウントを取得する
	// (GET /me)
	GetMe(c *gin.Context)
	// CreateStoreApplication 店舗の作成申請を作成する
	// (POST /store-applications)
	CreateStoreApplication(c *gin.Context)
	// GetApprovedStores 承認済みの店舗一覧を取得する
	// (GET /stores)
	GetApprovedStores(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// CreateStoreApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateStoreApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStoreApplication(c)
}

// GetApprovedStores operation middleware
func (siw *ServerInterfaceWrapper) GetApprovedStores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApprovedStores(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/store-applications", wrapper.CreateStoreApplication)
	router.GET(options.BaseURL+"/stores", wrapper.GetApprovedStores)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhdbxNHF/4rr+bt5cZ2gFTUd6FFlFJoRFT1gkZosjtJBrwfnRkDFrLk2Q0okKRBlBCljYqgKQkxcUCo",
	"wkCAH3OydvgX1cz6a+N1TCtIuVnCembO85yP55zZq8h0bc91iCM4yl5F3JwiNtZ/fskIFmRUuIwMe16O",
	"mlhQ1zlLuOc6nKgVHnM9wgQlej211NMi3GTUU0tRFoUvl3Znlup3nu2WZ0FWTn4FJT+8fu1dsF7/dRpk",
	"GeQWVwZ4ilog18NbczvVEpT8Hx1koAmX2VigLMrnqYUMJAoeQVnEBaPOJCoaiJFLlFweFVjkNYLPGJlA",
	"WfT/dJtTukEorXmc7dxQNBDPj9tUCGINC7W/ZdDCggwIapNuq9rsT3nKiIWy55AGFsMRP3WsdYA7foGY",
	"Qlk9zpjLevvRJpzjSf3D/rabC5NsnCBi2POYe4lYmjnvbc/CAuv4CWK/nxuVgYZFzBgu6P+7Aue6E6B2",
	"4+3uxnytOgPyLchKlA8gK/XnC7XFJ233UkeQScK6OGpwzdOTiH5NcE5M9WbHW9lBrmDby+ndF/vGtbEt",
	"yeJpso8vKfdyuHAG20nxMxCxMc3FUi16k5DcUTn1rQGPmiLPyPdMH+vkczk8rkgKlidJJePmNDLi5O0o",
	"h+xxwpCBsGVTp4PvfvnexNzJNoakYSfJe1ECdTuuM2uu/mtvUBtPNn3R9aPTKyrMde3+5aYtOhFXvcOI",
	"oe4w3pP32T2C1YyCRxxLmTQQbhStVhW1l1jJQeHEzDMqCqOqMCMfDpumm3fEKOG84UaqStB03YuUNLFn",
	"EeXm+QnCz+No+XneWN+uaY+eIgVUVGaoM+Fq11CRa2wemCD8f8MjJ5GBLhEWmUKZ1GAqo3i6HnGwR1EW",
	"HU5lUodVXmAxpfGlp3Stqj8niRZclQG6q5y0UFZpVlTNmnxUYnrjoUxG/WO6jiCO3ojbDSl9gUdkI4nq",
	"J2B79EKTjEvWd6fU26KB0lG69MJ6mnxMnB0qk4ARgk3wn4C/CsGzneomyAr4D8Avg/8QgmcQzKhQHMkM",
	"fjA48Z6VgKi2stEJCuQbkPdAboH/CoIA/OcQrOn3c/Xp++HNFwrg0Af0V1+A4P8FwTYEt9TTX4fgEQTb",
	"sVJC2XPdRXRurDimWrptY1Z4H8+DfztcuBu+WQK5DP6stpDWQ85ABzudL57LE1Iree5CkRgRLo65VmGP",
	"2+x8TlAPM5FWCjnQ7Ohtz+0rtu3GGK7e1SErQ7DReJakZrmlmAWbjaes6OD+Up/eBjkPck1xLfnIQDa+",
	"8i1xJlWVD2YyGQPZ1Gm96CXYvefGV2GwACX/m5HjJ6AkR86o5w9kfARkOdx6E75diZysJ8baSilcXYNg",
	"Efz7Oj5lFXJ/FfyXILcGM6ePdQ2W49RRUTV694q2bzoZh09nu7j2pdrsMq0jP88MxQ4Z6nfGnobUtxcl",
	"NKL4GWpIKHaJ2IdTjT5XiIQqjV0Y/Ns7r1dqM7dALoG8F0naQSqGKoItpRX+CwhmwtcPwu0FkHM71fna",
	"5h//tcJG9r84SAGN65ycU8Wnar/cHOurtRul8OnvOl4PQU5r/TPQkcHDBwszCCBY0nK1DcENkIvgz4G8",
	"19ATOad0QunWMsifWxiHDg5jU7uabpIbIKcjdFGWaUSHDh0gomt/hjd/C0urrcbddFYlvH4trLyI5f2n",
	"0LgVigNMq4Y7tBJA8FhjqWqnlGrLfvQ1I5x5VL+zrktiPorpP58vWjfkSPq6lHDPTMH3m1DjXwA+5rTa",
	"+3NDkpAlfRPYqZZ2H659SlNhKyT74O0e9nS8mboY6XB3j+3KThmC8ru7s/Xll/XbT8IHATJQXl1a0ZQQ",
	"Xjadzrkmzk25XGSPZo6qa1XXZ5WVx/XFjYTNPJtOY4+mJghP0cuY44s0hc3UBQ8Vx4p/BwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
