// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, google_sub, email, display_name, picture_url, role, last_login_at, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.PictureUrl,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (
    google_sub,
    email,
    display_name,
    picture_url
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (google_sub)
DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    picture_url = EXCLUDED.picture_url,
    last_login_at = now(),
    updated_at = now()
RETURNING id, google_sub, email, display_name, picture_url, role, last_login_at, created_at, updated_at
`

type UpsertAccountParams struct {
	GoogleSub   string  `json:"google_sub"`
	Email       string  `json:"email"`
	DisplayName string  `json:"display_name"`
	PictureUrl  *string `json:"picture_url"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.GoogleSub,
		arg.Email,
		arg.DisplayName,
		arg.PictureUrl,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.PictureUrl,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
