// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_membership_applications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getStoreMembershipApplicationsByStoreID = `-- name: GetStoreMembershipApplicationsByStoreID :many
SELECT id, store_id, account_id, status, reviewed_by, rejection_reason, submitted_at, reviewed_at
FROM store_membership_applications
WHERE store_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) GetStoreMembershipApplicationsByStoreID(ctx context.Context, storeID uuid.UUID) ([]StoreMembershipApplication, error) {
	rows, err := q.db.Query(ctx, getStoreMembershipApplicationsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreMembershipApplication{}
	for rows.Next() {
		var i StoreMembershipApplication
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.AccountID,
			&i.Status,
			&i.ReviewedBy,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
