// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignStoreToAccount = `-- name: AssignStoreToAccount :exec
UPDATE accounts
SET
    store_id = $2,
    updated_at = now()
WHERE id = $1
`

type AssignStoreToAccountParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) AssignStoreToAccount(ctx context.Context, arg AssignStoreToAccountParams) error {
	_, err := q.db.Exec(ctx, assignStoreToAccount, arg.ID, arg.StoreID)
	return err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    id,
    name,
    room,
    description,
    image_object_key,
    review_status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
`

type CreateStoreParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Room           string    `json:"room"`
	Description    string    `json:"description"`
	ImageObjectKey string    `json:"image_object_key"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.ID,
		arg.Name,
		arg.Room,
		arg.Description,
		arg.ImageObjectKey,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForStoreApplication = `-- name: GetAccountForStoreApplication :one
SELECT id, store_id
FROM accounts
WHERE id = $1
FOR UPDATE
`

type GetAccountForStoreApplicationRow struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) GetAccountForStoreApplication(ctx context.Context, id uuid.UUID) (GetAccountForStoreApplicationRow, error) {
	row := q.db.QueryRow(ctx, getAccountForStoreApplication, id)
	var i GetAccountForStoreApplicationRow
	err := row.Scan(&i.ID, &i.StoreID)
	return i, err
}
