/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ログイン中のアカウントを取得する */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 自分の注文一覧を取得する
     * @description Guestセッションに紐づく自分の注文を全店舗横断で、新しい注文から取得する。
     *     statusesを省略した場合はすべての状態を対象にする。
     *     Guestセッションが未発行の場合は空の一覧を返し、GETではGuestを新規発行しない。
     *     注文後の店舗の閉店・販売状況にかかわらず取得できる。
     */
    get: operations["getOrders"];
    put?: never;
    /**
     * カートから注文を確定する
     * @description 同じGuest・店舗・元カートversionの再送は、現在の販売状況や権限にかかわらず同じ注文を返す。
     *     通常のpending/ready注文は全店舗合計で2件まで。当該店舗のStaff/Managerによる注文は件数制限を免除し、集計から除外する。
     *     成功時は同じカートの明細を消去してversionを1増やす。明細順序は保証しない。
     */
    post: operations["createOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 自分の注文詳細を取得する
     * @description Guestセッションに紐づく自分の注文を取得する。
     *     Guestセッションが未発行の場合、注文が存在しない場合、自分の注文でない場合は404を返す。
     *     GETではGuestを新規発行しない。注文後の店舗の閉店・販売状況にかかわらず取得できる。
     *     現時点ではダミー実装として404を返す。
     */
    get: operations["getOrderByID"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 店舗の注文一覧を取得する
     * @description 店舗の注文一覧を取得する。
     */
    get: operations["getOrdersByStoreID"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 店舗の注文状態を更新する
     * @description 店舗に所属する注文の状態を更新する。
     */
    patch: operations["updateOrderByStoreIDAndOrderID"];
    trace?: never;
  };
  "/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * アプリの利用体験に対するレビューを投稿する
     * @description ゲスト・店舗側のどちらからでも投稿できるアプリへのレビュー。
     *     ログインは不要。既存のゲスト・アカウントセッションがある場合だけ投稿者IDを保存する。
     *     投稿のためにゲストセッションを新規発行しない。
     *     投稿元の操作はtriggerで記録する。レビュー表示の抽選と1日間隔の制御はフロントエンドが行う。
     */
    post: operations["createReview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 利用可能な教室一覧を取得する */
    get: operations["getRooms"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 画像をアップロードする */
    post: operations["uploadImage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/store-applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗申請一覧を取得する */
    get: operations["getStoreApplications"];
    put?: never;
    /** 店舗の作成申請を作成する */
    post: operations["createStoreApplication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/store-applications/review-status/{store_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 店舗申請の審査ステータスを更新する */
    put: operations["updateStoreApplicationReviewStatus"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 閲覧可能な店舗一覧を取得する */
    get: operations["getVisibleStores"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 承認済みの店舗を取得する */
    get: operations["getApprovedStoreByID"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 店舗情報を部分更新する */
    patch: operations["updateStore"];
    trace?: never;
  };
  "/stores/{store_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のメンバー一覧を取得する */
    get: operations["getStoreMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/members/{account_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のメンバーを取得する */
    get: operations["getStoreMemberByStoreIDAndAccountID"];
    put?: never;
    post?: never;
    /** 店舗のメンバーを削除する */
    delete: operations["removeStoreMember"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/menus": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のメニュー一覧を取得する */
    get: operations["getMenusByStoreID"];
    put?: never;
    /** 店舗のメニューを作成する */
    post: operations["createMenu"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/menus/{menu_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 店舗のメニューを削除する */
    delete: operations["deleteMenuByStoreIDAndMenuID"];
    options?: never;
    head?: never;
    /** 店舗のメニューを更新する */
    patch: operations["updateMenuByStoreIDAndMenuID"];
    trace?: never;
  };
  "/stores/{store_id}/menus/{menu_id}/toppings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のメニューで選択可能なトッピング一覧を取得する */
    get: operations["getToppingsByStoreIDAndMenuID"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/toppings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のトッピング一覧を取得する */
    get: operations["getToppingsByStoreID"];
    put?: never;
    /** 店舗のトッピングを作成する */
    post: operations["createTopping"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/toppings/{topping_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 店舗のトッピングを削除する（紐づけられているメニューのトッピングも削除される） */
    delete: operations["deleteToppingByStoreIDAndToppingID"];
    options?: never;
    head?: never;
    /** 店舗のトッピングを更新する */
    patch: operations["updateToppingByStoreIDAndToppingID"];
    trace?: never;
  };
  "/stores/{store_id}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 店舗のメンバー招待を作成する */
    post: operations["createStoreInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/carts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗の自分のカートを取得する（Guest セッションがない場合は空カートが返る） */
    get: operations["getStoreCart"];
    /**
     * 店舗の自分のカートを更新する（Guestセッションがない場合、カートがない場合はそれぞれが新規作成される）
     * @description 新しく選ぶトッピングは対象メニューに紐づく同店舗のものに限る。同じ明細に保存済みの選択は関連解除後も保持・削除できる。
     */
    put: operations["updateStoreCart"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/store-invitations/{invitation_id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 店舗のメンバー招待を受け入れる */
    post: operations["acceptStoreInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/allergens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** アレルゲン一覧を取得する */
    get: operations["getAllergens"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateReviewInput: {
      /**
       * Format: int32
       * @description アプリへの満足度（1〜5の星）
       */
      rating: number;
      /** @description 任意の感想・要望。空白のみの場合は未入力として保存する。 */
      comment?: string | null;
      /**
       * @description フロントエンドで何をトリガーにレビューモーダルを表示したかを識別するための文字列。
       *     これにより、レビューがどのような操作をしていたユーザーによるものかが保存できる。
       * @example order_complete
       */
      trigger?: string | null;
    };
    CreateReviewResponse: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      createdAt: string;
    };
    HealthResponse: {
      /** @example ok */
      status: string;
      /**
       * @description 稼働中のイメージの元となったGit Commit SHA
       * @example 0123456789abcdef0123456789abcdef01234567
       */
      commitHash: string;
      /**
       * Format: date-time
       * @description デプロイされた日時（正確にはビルドされた日時だが、最大でも数分程度の誤差のはず）
       * @example 2026-08-29T12:34:56Z
       */
      deployedAt: string;
    };
    MeResponse: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      displayName: string;
      pictureUrl: string | null;
      /** @enum {string} */
      role: "member" | "admin";
    };
    GetRoomsResponse: {
      /** @description ルームの総数 */
      total: number;
      data: components["schemas"]["Room"][];
    };
    Room: {
      name: string;
    };
    /** @enum {string} */
    StoreReviewStatus: "pending" | "approved" | "rejected";
    /** @example images/e625d731-8d26-4de9-ac77-a1bc96affb8e */
    ImageObjectKey: string;
    UploadImageResponse: {
      imageObjectKey: components["schemas"]["ImageObjectKey"];
    };
    CreateStoreApplicationInput: {
      /** @example たこ焼き屋 */
      name: string;
      /** @example 605教室 */
      room: string;
      /** @example 外はカリカリ、中はトロトロのたこ焼きです。 */
      description: string;
      /** @description 店舗で使用するアレルゲンのID一覧。該当するアレルゲンがない場合は空配列。 */
      allergenIds: string[];
      imageObjectKey: components["schemas"]["ImageObjectKey"];
    };
    CreateStoreApplicationResponse: {
      /**
       * Format: uuid
       * @description 店舗申請のID。内部的にはstores.idと同一。
       */
      id: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
      /** Format: date-time */
      submittedAt: string;
    };
    GetAllergensResponse: {
      /** @description アレルゲンの総数 */
      total: number;
      data: components["schemas"]["Allergen"][];
    };
    Allergen: {
      /** Format: uuid */
      id: string;
      name: string;
    };
    GetStoreMembersResponse: {
      /** @description 店舗メンバーの総数 */
      total: number;
      data: components["schemas"]["StoreMember"][];
    };
    UpdateStoreApplicationReviewStatusResponse: {
      /**
       * Format: uuid
       * @description 店舗申請のID。内部的にはstores.idと同一。
       */
      id: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
    };
    GetMenusByStoreIDResponse: {
      /** @description 店舗メニューの総数 */
      total: number;
      data: components["schemas"]["Menu"][];
    };
    GetToppingsByStoreIDResponse: {
      /** @description 店舗トッピングの総数 */
      total: number;
      data: components["schemas"]["Topping"][];
    };
    GetToppingsByStoreIDAndMenuIDResponse: {
      /** @description メニューで選択可能なトッピングの総数 */
      total: number;
      data: components["schemas"]["Topping"][];
    };
    /** @enum {string} */
    StoreMemberRole: "staff" | "manager";
    CreateStoreInvitationResponse: {
      /**
       * Format: uuid
       * @description 店舗メンバー招待のID。内部的にはstore_invitations.idと同一。
       */
      id: string;
      /** Format: uuid */
      storeId: string;
      role: components["schemas"]["StoreMemberRole"];
      /**
       * Format: int32
       * @description 招待リンクの最大使用回数。nullの場合は無制限。
       */
      maxUses: number | null;
      /** Format: date-time */
      createdAt: string;
    };
    GetVisibleStoresResponse: {
      /** @description 閲覧可能な店舗の総数 */
      total: number;
      data: components["schemas"]["Store"][];
    };
    GetStoreApplicationsResponse: {
      /** @description 店舗申請の総数 */
      total: number;
      data: components["schemas"]["StoreApplication"][];
    };
    AcceptStoreInvitationResponse: {
      /** Format: uuid */
      storeId: string;
      role: components["schemas"]["StoreMemberRole"];
    };
    GetOrdersResponse: {
      /** @description 指定した条件に一致する注文の総数 */
      total: number;
      data: components["schemas"]["Order"][];
    };
    UpdateOrderInput: {
      status: components["schemas"]["OrderStatus"];
      /**
       * Format: int32
       * @description 更新対象の注文のversion。同じ状態への再送にも同じ値を使用する。
       */
      expectedVersion: number;
    };
    CreateOrderInput: {
      /** Format: uuid */
      storeId: string;
      /**
       * Format: int32
       * @description 注文に使うカートのversion。成立済み注文の再送にも同じ値を使用する。
       */
      expectedCartVersion: number;
    };
    /** @enum {string} */
    OrderStatus: "pending" | "ready" | "completed" | "cancelled";
    Order: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      storeId: string;
      status: components["schemas"]["OrderStatus"];
      /**
       * Format: int64
       * @description トッピングを含む合計金額（円）
       */
      totalAmount: number;
      /** Format: int32 */
      displayNumber: number;
      /** Format: int32 */
      version: number;
      /** @description 注文時の店舗名 */
      storeName: string;
      /** @description 注文時の教室名 */
      roomName: string;
      /** @description 注文時の明細。カート内の順序は保証しない。 */
      items: components["schemas"]["OrderItem"][];
      /** Format: date-time */
      readyAt: string | null;
      /** Format: date-time */
      completedAt: string | null;
      /** Format: date-time */
      cancelledAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    OrderItem: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      menuId: string;
      menuName: string;
      /** Format: int32 */
      unitPrice: number;
      /** Format: int32 */
      quantity: number;
      toppings: components["schemas"]["OrderItemTopping"][];
    };
    OrderItemTopping: {
      /** Format: uuid */
      toppingId: string;
      toppingName: string;
      /** Format: int32 */
      unitPrice: number;
    };
    UpdateCartInput: {
      /**
       * Format: int32
       * @description カートの更新前のバージョン。カートの更新時に、この値と現在のカートのバージョンが一致しない場合は409 Conflict
       */
      expectedVersion: number;
      items: components["schemas"]["UpdateCartItemInput"][];
    };
    UpdateCartItemInput: {
      /**
       * Format: uuid
       * @description カートアイテムのID。新規追加の場合は省略する。既存のカートアイテムを更新する場合は指定する。
       */
      id?: string;
      /** Format: uuid */
      menuId: string;
      /** Format: int32 */
      quantity: number;
      toppingIds: string[];
    };
    Cart: {
      /** Format: uuid */
      storeId: string;
      /** Format: int32 */
      version: number;
      totalAmount: number;
      /** @description カートの内容で注文可能かどうか。店舗が閉店している場合、カートに利用できないアイテムが含まれている場合、カートがからの場合はfalseになる。 */
      canCheckout: boolean;
      items: components["schemas"]["CartItem"][];
    };
    CartItem: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      menuId: string;
      name: string;
      imageUrl: string;
      /** @description メニューが現在利用可能かどうか。店舗がメニューを削除した場合や売り切れはfalseになる。 */
      available: boolean;
      /** Format: int32 */
      quantity: number;
      /** Format: int32 */
      unitPrice: number;
      toppings: components["schemas"]["CartItemTopping"][];
    };
    CartItemTopping: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      cartItemId: string;
      /** Format: uuid */
      toppingId: string;
      name: string;
      /** Format: int32 */
      unitPrice: number;
      /** @description トッピングが現在利用可能かどうか。削除・売り切れ・対象メニューとの関連解除の場合はfalseになる。選択自体はカートに残る。 */
      available: boolean;
    };
    /**
     * Format: int32
     * @description 店舗の混雑度。1、2、3の3段階で、3が最も混んでいる。新規店舗と既存店舗の初期値は1。
     * @enum {integer}
     */
    StoreCongestionLevel: 1 | 2 | 3;
    Store: {
      /** Format: uuid */
      id: string;
      name: string;
      room: string;
      description: string;
      imageUrl: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
      allergens: components["schemas"]["Allergen"][];
      /** Format: date-time */
      closedAt: string | null;
      congestionLevel: components["schemas"]["StoreCongestionLevel"];
    };
    /** @description 指定した項目のみ更新する。混雑度も省略した場合は変更しない。 */
    UpdateStoreInput: {
      congestionLevel?: components["schemas"]["StoreCongestionLevel"];
      /** @description trueで閉店、falseで営業再開する */
      closed?: boolean;
      /** @example 605教室 */
      room?: string;
      imageObjectKey?: components["schemas"]["ImageObjectKey"];
      description?: string;
      /** @description 店舗で使用するアレルゲンのID一覧。空配列で表示を消去する。 */
      allergenIds?: string[];
    };
    StoreMember: {
      /** Format: uuid */
      storeId: string;
      /** Format: uuid */
      accountId: string;
      role: components["schemas"]["StoreMemberRole"];
      /** Format: date-time */
      joinedAt: string;
      displayName: string;
      pictureUrl: string | null;
    };
    StoreApplication: {
      /** Format: uuid */
      id: string;
      name: string;
      room: string;
      description: string;
      imageUrl: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
      /** Format: date-time */
      submittedAt: string;
      congestionLevel: components["schemas"]["StoreCongestionLevel"];
      allergens: components["schemas"]["Allergen"][];
    };
    Menu: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      storeId: string;
      name: string;
      description: string;
      /** Format: int32 */
      unitPrice: number;
      imageUrl: string;
      soldOut: boolean;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      createdAt: string;
    };
    CreateToppingInput: {
      /** @example チーズ */
      name: string;
      /**
       * Format: int32
       * @example 100
       */
      unitPrice: number;
    };
    UpdateToppingInput: {
      /** @example チーズ */
      name?: string;
      /**
       * Format: int32
       * @example 100
       */
      unitPrice?: number;
      soldOut?: boolean;
    };
    CreateMenuInput: {
      /** @example たこ焼き */
      name: string;
      /** @example 外はカリカリ、中はトロトロのたこ焼きです。 */
      description: string;
      /**
       * Format: int32
       * @example 500
       */
      unitPrice: number;
      /** @description 対象のメニューにトッピング可能なトッピングのID一覧。空配列も可。 */
      toppingIds?: string[];
      imageObjectKey: components["schemas"]["ImageObjectKey"];
    };
    UpdateMenuInput: {
      /** @example たこ焼き */
      name?: string;
      /** @example 外はカリカリ、中はトロトロのたこ焼きです。 */
      description?: string;
      /**
       * Format: int32
       * @example 500
       */
      unitPrice?: number;
      /** @description 対象のメニューにトッピング可能なトッピングのID一覧。空配列も可。 */
      toppingIds?: string[];
      soldOut?: boolean;
      imageObjectKey?: components["schemas"]["ImageObjectKey"];
    };
    Topping: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      storeId: string;
      name: string;
      /** Format: int32 */
      unitPrice: number;
      soldOut: boolean;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      createdAt: string;
    };
    ErrorResponse: {
      message: string;
    };
  };
  responses: never;
  parameters: {
    /**
     * @description 取得対象の注文状態。複数指定はOR条件。
     *     statuses=pending&statuses=readyのように同じキーを繰り返して指定する。
     * @example [
     *       "pending",
     *       "ready"
     *     ]
     */
    OrderStatuses: components["schemas"]["OrderStatus"][];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ログイン中のアカウント */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description 未ログインまたはセッションが無効 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getOrders: {
    parameters: {
      query?: {
        /**
         * @description 取得対象の注文状態。複数指定はOR条件。
         *     statuses=pending&statuses=readyのように同じキーを繰り返して指定する。
         * @example [
         *       "pending",
         *       "ready"
         *     ]
         */
        statuses?: components["parameters"]["OrderStatuses"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 自分の注文一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetOrdersResponse"];
        };
      };
      /** @description クエリパラメータが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderInput"];
      };
    };
    responses: {
      /** @description 成立済み注文への再送 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description 注文を作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description 空カート・数量・メニュー種類数などの入力が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認されていない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description カートversion競合・閉店・利用不可の選択・同時注文件数制限 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getOrderByID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 自分の注文詳細 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description 注文IDの形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 注文が存在しない、または自分の注文ではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getOrdersByStoreID: {
    parameters: {
      query?: {
        /**
         * @description 取得対象の注文状態。複数指定はOR条件。
         *     statuses=pending&statuses=readyのように同じキーを繰り返して指定する。
         * @example [
         *       "pending",
         *       "ready"
         *     ]
         */
        statuses?: components["parameters"]["OrderStatuses"];
      };
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description 当該店舗のStaff/Managerの場合、全Guestの注文を注文時の明細付きで古い注文から返す。
       *     statusesを省略した場合はpending/ready、指定した場合は指定した状態のいずれかに一致する注文を返す。
       *     キッチンはstatuses=pending、受け渡しはstatuses=pending&statuses=readyで取得できる。
       *     店舗の閉店・現在の販売状況にかかわらず取得でき、該当する注文がなければ空の一覧を返す。
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetOrdersResponse"];
        };
      };
      /** @description 店舗IDがUUID形式ではない、またはstatusesに不正な値・重複した値を指定した場合。 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログインまたはセッションが無効 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description ログイン中のAccountが当該店舗のStaff/Managerではない場合。Adminというだけでは閲覧できない。 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateOrderByStoreIDAndOrderID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        order_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderInput"];
      };
    };
    responses: {
      /**
       * @description 状態更新に成功した場合、更新後の注文を返す。更新時刻はサーバー側で決定する。
       *     すでに要求したstatusの場合はexpectedVersionにかかわらず同じ注文を返し、version・日時を変更しない。
       *     店舗の閉店・現在の販売状況は状態更新を妨げない。
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /**
       * @description 店舗ID・注文IDがUUID形式ではない、必須項目がない、statusが定義された値ではない、
       *     expectedVersionが1以上の整数ではない、またはリクエスト形式が不正な場合。
       *     status・expectedVersion以外の項目（金額・明細など）を指定した場合も返す。
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Accountセッションが存在しない、無効、または有効期限切れの場合。 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description ログイン中のAccountが当該店舗のStaff/Managerではない場合。 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または指定した注文が当該店舗に存在しない場合。 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /**
       * @description 要求したstatusが現在と異なり、expectedVersionが現在のversionと一致しない場合。
       *     pendingからready、readyからcompletedまたはcancelled以外の状態遷移を要求した場合。
       *     readyからcancelledへの遷移を、呼び出し開始（readyAt）から15分が経過する前に要求した場合。
       */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 注文の読み取り・更新など、サーバー内部の処理で予期しないエラーが発生した場合。 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /**
       * @description 現時点ではインターフェースのみの実装のため、リクエスト形式とAccountセッションの検証を通過した場合に返す。
       *     店舗の存在・Membership・注文の検証と状態更新は未実装。
       */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createReview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateReviewInput"];
      };
    };
    responses: {
      /** @description レビューを投稿した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateReviewResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getRooms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 教室一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetRoomsResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  uploadImage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description 画像。JPEG、PNG、WebPに対応する。
           *     最大ファイルサイズは10MB。
           */
          image: string;
        };
      };
    };
    responses: {
      /** @description 画像をアップロードした */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadImageResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description アップロードされた画像が大きすぎる */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 対応していない画像形式 */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 画像の内容が不正 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 画像ストレージが一時的に利用できない */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreApplications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗申請一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetStoreApplicationsResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 管理者権限がない */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createStoreApplication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStoreApplicationInput"];
      };
    };
    responses: {
      /** @description 店舗申請を作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateStoreApplicationResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateStoreApplicationReviewStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          reviewStatus: components["schemas"]["StoreReviewStatus"];
        };
      };
    };
    responses: {
      /** @description 店舗申請の審査ステータスを更新した */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateStoreApplicationReviewStatusResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 管理者権限がない */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗申請が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 更新できない審査ステータスへの変更 approved -> approved など */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getVisibleStores: {
    parameters: {
      query?: {
        /** @description true の場合、ログイン中のアカウントが所属する承認済み・申請中の店舗を取得する */
        member_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗一覧。member_only が false の場合は承認済みの店舗と自分が管理者である申請中の店舗 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetVisibleStoresResponse"];
        };
      };
      /** @description クエリパラメータが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description member_only が true で未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getApprovedStoreByID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗情報 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Store"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateStore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateStoreInput"];
      };
    };
    responses: {
      /** @description 更新後の店舗情報 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Store"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗の管理権限がない */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメンバー一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetStoreMembersResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または店舗のメンバーではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreMemberByStoreIDAndAccountID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメンバー */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoreMember"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または対象が店舗のメンバーではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  removeStoreMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメンバーを削除した */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（自分が店舗管理者ではない、対象が店舗管理者である） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または対象が店舗のメンバーではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMenusByStoreID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメニュー一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetMenusByStoreIDResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createMenu: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMenuInput"];
      };
    };
    responses: {
      /** @description 店舗のメニューを作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Menu"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はメニューを登録できない） */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteMenuByStoreIDAndMenuID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        menu_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメニューを削除した */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はメニューを削除できない）、またはメニューが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateMenuByStoreIDAndMenuID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        menu_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMenuInput"];
      };
    };
    responses: {
      /** @description 店舗のメニューを更新した */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Menu"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はメニューを更新できない）、またはメニューが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getToppingsByStoreIDAndMenuID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        menu_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメニューで選択可能なトッピング一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetToppingsByStoreIDAndMenuIDResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、承認済みではない、またはメニューが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getToppingsByStoreID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のトッピング一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetToppingsByStoreIDResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗に所属していない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createTopping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateToppingInput"];
      };
    };
    responses: {
      /** @description 店舗のトッピングを作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Topping"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はトッピングを登録できない） */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteToppingByStoreIDAndToppingID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        topping_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のトッピングを削除した */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はトッピングを削除できない）、またはトッピングが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateToppingByStoreIDAndToppingID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
        topping_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateToppingInput"];
      };
    };
    responses: {
      /** @description 店舗のトッピングを更新した */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Topping"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗のメンバーでない、または店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない（未承認の店舗はトッピングを更新できない）、またはトッピングが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createStoreInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: int32
           * @description 招待リンクの最大使用回数。省略時は無制限。
           * @default null
           */
          maxUses?: number | null;
          role: components["schemas"]["StoreMemberRole"];
        };
      };
    };
    responses: {
      /** @description 店舗のメンバー招待を作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateStoreInvitationResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗マネージャーでない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しないか、店舗のメンバーではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreCart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のカート */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateStoreCart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCartInput"];
      };
    };
    responses: {
      /** @description 店舗のカートを更新した */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない、または承認済みではない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description expectedVersion が一致しない（カートの更新競合） */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  acceptStoreInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメンバー招待を受け入れた */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AcceptStoreInvitationResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 招待が存在しない、使用回数が上限に達している */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description すでに招待された権限以上で店舗のメンバーである */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getAllergens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description アレルゲン一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetAllergensResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
