/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ログイン中のアカウントを取得する */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/store-applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗申請一覧を取得する */
    get: operations["getStoreApplications"];
    put?: never;
    /** 店舗の作成申請を作成する */
    post: operations["createStoreApplication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/store-applications/review-status/{store_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 店舗申請の審査ステータスを更新する */
    put: operations["updateStoreApplicationReviewStatus"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 承認済みの店舗一覧を取得する */
    get: operations["getApprovedStores"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stores/{store_id}/membership-applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 店舗のメンバー申請一覧を取得する */
    get: operations["getStoreMembershipApplicationsByStoreID"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      /** @example ok */
      status: string;
    };
    MeResponse: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      displayName: string;
      pictureUrl: string | null;
      /** @enum {string} */
      role: "member" | "admin";
    };
    /** @enum {string} */
    StoreReviewStatus: "pending" | "approved" | "rejected";
    CreateStoreApplicationResponse: {
      /**
       * Format: uuid
       * @description 店舗申請のID。内部的にはstores.idと同一。
       */
      id: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
      /** Format: date-time */
      submittedAt: string;
    };
    UpdateStoreApplicationReviewStatusResponse: {
      /**
       * Format: uuid
       * @description 店舗申請のID。内部的にはstores.idと同一。
       */
      id: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
    };
    GetApprovedStoresResponse: {
      /** @description 承認済みの店舗の総数 */
      total: number;
      data: components["schemas"]["Store"][];
    };
    GetStoreApplicationsResponse: {
      /** @description 店舗申請の総数 */
      total: number;
      data: components["schemas"]["StoreApplication"][];
    };
    GetStoreMembershipApplicationsResponse: {
      /** @description 店舗のメンバー申請の総数 */
      total: number;
      data: components["schemas"]["StoreMembershipApplication"][];
    };
    StoreMembershipApplication: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      storeId: string;
      /** Format: uuid */
      accountId: string;
      status: components["schemas"]["StoreMembershipApplicationStatus"];
      /** Format: uuid */
      reviewedBy: string | null;
      /** Format: date-time */
      reviewedAt: string | null;
      rejectionReason: string | null;
      /** Format: date-time */
      submittedAt: string;
    };
    /** @enum {string} */
    StoreMembershipApplicationStatus: "pending" | "approved" | "rejected";
    Store: {
      /** Format: uuid */
      id: string;
      name: string;
      room: string;
      description: string;
      imageUrl: string;
    };
    StoreApplication: {
      /** Format: uuid */
      id: string;
      name: string;
      room: string;
      description: string;
      imageUrl: string;
      reviewStatus: components["schemas"]["StoreReviewStatus"];
      /** Format: date-time */
      submittedAt: string;
    };
    ErrorResponse: {
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ログイン中のアカウント */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description 未ログインまたはセッションが無効 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreApplications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗申請一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetStoreApplicationsResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 管理者権限がない */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createStoreApplication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** @example たこ焼き屋 */
          name: string;
          /** @example 605 */
          room: string;
          /** @example 外はカリカリ、中はトロトロのたこ焼きです。 */
          description: string;
          /**
           * Format: binary
           * @description 店舗画像。JPEG、PNG、WebPに対応する。
           *     最大ファイルサイズは10MB。
           */
          image: string;
        };
      };
    };
    responses: {
      /** @description 店舗申請を作成した */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateStoreApplicationResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description アップロードされた画像が大きすぎる */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 対応していない画像形式 */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 入力値または画像の内容が不正 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 画像ストレージが一時的に利用できない */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateStoreApplicationReviewStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          reviewStatus: components["schemas"]["StoreReviewStatus"];
        };
      };
    };
    responses: {
      /** @description 店舗申請の審査ステータスを更新した */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateStoreApplicationReviewStatusResponse"];
        };
      };
      /** @description リクエスト形式が不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 管理者権限がない */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗申請が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 更新できない審査ステータスへの変更 approved -> approved など */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getApprovedStores: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 承認済みの店舗一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetApprovedStoresResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStoreMembershipApplicationsByStoreID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        store_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 店舗のメンバー申請一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetStoreMembershipApplicationsResponse"];
        };
      };
      /** @description 未ログイン */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 権限不足（店舗マネージャー、管理者でない） */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 店舗が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description サーバーエラー */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
