// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allergens.sql

package sqlc

import (
	"context"
)

const getAllergens = `-- name: GetAllergens :many
SELECT id, name
FROM allergens
`

func (q *Queries) GetAllergens(ctx context.Context) ([]Allergen, error) {
	rows, err := q.db.Query(ctx, getAllergens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Allergen{}
	for rows.Next() {
		var i Allergen
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
