// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpCartVersion = `-- name: BumpCartVersion :one
UPDATE carts
SET version = version + 1
WHERE guest_id = $1
  AND store_id = $2
  AND version = $3
RETURNING id, version
`

type BumpCartVersionParams struct {
	GuestID         uuid.UUID `json:"guest_id"`
	StoreID         uuid.UUID `json:"store_id"`
	ExpectedVersion int32     `json:"expected_version"`
}

type BumpCartVersionRow struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

func (q *Queries) BumpCartVersion(ctx context.Context, arg BumpCartVersionParams) (BumpCartVersionRow, error) {
	row := q.db.QueryRow(ctx, bumpCartVersion, arg.GuestID, arg.StoreID, arg.ExpectedVersion)
	var i BumpCartVersionRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (guest_id, store_id)
VALUES ($1, $2)
RETURNING id, guest_id, store_id, version
`

type CreateCartParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.GuestID, arg.StoreID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.StoreID,
		&i.Version,
	)
	return i, err
}

const deleteCartItemToppingsNotIn = `-- name: DeleteCartItemToppingsNotIn :exec
DELETE FROM cart_item_toppings AS cit
USING cart_items AS ci
WHERE ci.id = cit.cart_item_id
  AND ci.cart_id = $1
  AND ci.store_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM ROWS FROM (
          unnest($3::uuid[]),
          unnest($4::uuid[])
      ) AS desired(cart_item_id, topping_id)
      WHERE desired.cart_item_id = cit.cart_item_id
        AND desired.topping_id = cit.topping_id
  )
`

type DeleteCartItemToppingsNotInParams struct {
	CartID      uuid.UUID   `json:"cart_id"`
	StoreID     uuid.UUID   `json:"store_id"`
	CartItemIds []uuid.UUID `json:"cart_item_ids"`
	ToppingIds  []uuid.UUID `json:"topping_ids"`
}

func (q *Queries) DeleteCartItemToppingsNotIn(ctx context.Context, arg DeleteCartItemToppingsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemToppingsNotIn,
		arg.CartID,
		arg.StoreID,
		arg.CartItemIds,
		arg.ToppingIds,
	)
	return err
}

const deleteCartItemsNotIn = `-- name: DeleteCartItemsNotIn :exec
DELETE FROM cart_items
WHERE cart_id = $1
  AND NOT (
      id = ANY($2::uuid[])
  )
`

type DeleteCartItemsNotInParams struct {
	CartID           uuid.UUID   `json:"cart_id"`
	RemainingItemIds []uuid.UUID `json:"remaining_item_ids"`
}

func (q *Queries) DeleteCartItemsNotIn(ctx context.Context, arg DeleteCartItemsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemsNotIn, arg.CartID, arg.RemainingItemIds)
	return err
}

const getCartByGuestIDAndStoreID = `-- name: GetCartByGuestIDAndStoreID :many
SELECT
    carts.id AS cart_id,
    carts.version AS cart_version,
    carts.guest_id,
    carts.store_id,

    cart_items.id AS cart_item_id,
    cart_items.quantity AS cart_item_quantity,
    cart_items.created_at AS cart_item_created_at,

    menus.id AS menu_id,
    menus.name AS menu_name,
    menus.unit_price AS menu_unit_price,
    menus.image_object_key AS menu_image_object_key,
    menus.sold_out AS menu_sold_out,
    menus.deleted_at AS menu_deleted_at,

    cart_item_toppings.id AS cart_item_topping_id,

    toppings.id AS topping_id,
    toppings.name AS topping_name,
    toppings.unit_price AS topping_unit_price,
    toppings.sold_out AS topping_sold_out,
    toppings.deleted_at AS topping_deleted_at
FROM carts
LEFT JOIN cart_items
    ON cart_items.cart_id = carts.id
    AND cart_items.store_id = carts.store_id
LEFT JOIN menus
    ON menus.id = cart_items.menu_id
    AND menus.store_id = cart_items.store_id
LEFT JOIN cart_item_toppings
    ON cart_item_toppings.cart_item_id = cart_items.id
    AND cart_item_toppings.menu_id = cart_items.menu_id
LEFT JOIN toppings
    ON toppings.id = cart_item_toppings.topping_id
WHERE carts.guest_id = $1
  AND carts.store_id = $2
ORDER BY
    cart_items.created_at ASC,
    cart_items.id ASC,
    toppings.id ASC
`

type GetCartByGuestIDAndStoreIDParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type GetCartByGuestIDAndStoreIDRow struct {
	CartID             uuid.UUID          `json:"cart_id"`
	CartVersion        int32              `json:"cart_version"`
	GuestID            uuid.UUID          `json:"guest_id"`
	StoreID            uuid.UUID          `json:"store_id"`
	CartItemID         *uuid.UUID         `json:"cart_item_id"`
	CartItemQuantity   *int32             `json:"cart_item_quantity"`
	CartItemCreatedAt  pgtype.Timestamptz `json:"cart_item_created_at"`
	MenuID             *uuid.UUID         `json:"menu_id"`
	MenuName           *string            `json:"menu_name"`
	MenuUnitPrice      *int32             `json:"menu_unit_price"`
	MenuImageObjectKey *string            `json:"menu_image_object_key"`
	MenuSoldOut        *bool              `json:"menu_sold_out"`
	MenuDeletedAt      pgtype.Timestamptz `json:"menu_deleted_at"`
	CartItemToppingID  *uuid.UUID         `json:"cart_item_topping_id"`
	ToppingID          *uuid.UUID         `json:"topping_id"`
	ToppingName        *string            `json:"topping_name"`
	ToppingUnitPrice   *int32             `json:"topping_unit_price"`
	ToppingSoldOut     *bool              `json:"topping_sold_out"`
	ToppingDeletedAt   pgtype.Timestamptz `json:"topping_deleted_at"`
}

func (q *Queries) GetCartByGuestIDAndStoreID(ctx context.Context, arg GetCartByGuestIDAndStoreIDParams) ([]GetCartByGuestIDAndStoreIDRow, error) {
	rows, err := q.db.Query(ctx, getCartByGuestIDAndStoreID, arg.GuestID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartByGuestIDAndStoreIDRow{}
	for rows.Next() {
		var i GetCartByGuestIDAndStoreIDRow
		if err := rows.Scan(
			&i.CartID,
			&i.CartVersion,
			&i.GuestID,
			&i.StoreID,
			&i.CartItemID,
			&i.CartItemQuantity,
			&i.CartItemCreatedAt,
			&i.MenuID,
			&i.MenuName,
			&i.MenuUnitPrice,
			&i.MenuImageObjectKey,
			&i.MenuSoldOut,
			&i.MenuDeletedAt,
			&i.CartItemToppingID,
			&i.ToppingID,
			&i.ToppingName,
			&i.ToppingUnitPrice,
			&i.ToppingSoldOut,
			&i.ToppingDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCartItemToppingsIfNotExists = `-- name: InsertCartItemToppingsIfNotExists :exec
INSERT INTO cart_item_toppings (
    cart_item_id,
    menu_id,
    topping_id
)
SELECT DISTINCT
    ci.id,
    ci.menu_id,
    desired.topping_id
FROM ROWS FROM (
    unnest($1::uuid[]),
    unnest($2::uuid[])
) AS desired(cart_item_id, topping_id)
INNER JOIN cart_items AS ci
    ON ci.id = desired.cart_item_id
WHERE ci.cart_id = $3
  AND ci.store_id = $4
ON CONFLICT (cart_item_id, topping_id) DO NOTHING
`

type InsertCartItemToppingsIfNotExistsParams struct {
	CartItemIds []uuid.UUID `json:"cart_item_ids"`
	ToppingIds  []uuid.UUID `json:"topping_ids"`
	CartID      uuid.UUID   `json:"cart_id"`
	StoreID     uuid.UUID   `json:"store_id"`
}

func (q *Queries) InsertCartItemToppingsIfNotExists(ctx context.Context, arg InsertCartItemToppingsIfNotExistsParams) error {
	_, err := q.db.Exec(ctx, insertCartItemToppingsIfNotExists,
		arg.CartItemIds,
		arg.ToppingIds,
		arg.CartID,
		arg.StoreID,
	)
	return err
}

const upsertCartItems = `-- name: UpsertCartItems :execrows
INSERT INTO cart_items (
    id,
    cart_id,
    menu_id,
    store_id,
    quantity
)
SELECT
    input.id,
    $1,
    input.menu_id,
    $2,
    input.quantity
FROM ROWS FROM (
    unnest($3::uuid[]),
    unnest($4::uuid[]),
    unnest($5::integer[])
) AS input(id, menu_id, quantity)
ON CONFLICT (id) DO UPDATE SET
    quantity = EXCLUDED.quantity
WHERE cart_items.cart_id = EXCLUDED.cart_id
  AND cart_items.store_id = EXCLUDED.store_id
  AND cart_items.menu_id = EXCLUDED.menu_id
`

type UpsertCartItemsParams struct {
	CartID     uuid.UUID   `json:"cart_id"`
	StoreID    uuid.UUID   `json:"store_id"`
	ItemIds    []uuid.UUID `json:"item_ids"`
	MenuIds    []uuid.UUID `json:"menu_ids"`
	Quantities []int32     `json:"quantities"`
}

func (q *Queries) UpsertCartItems(ctx context.Context, arg UpsertCartItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCartItems,
		arg.CartID,
		arg.StoreID,
		arg.ItemIds,
		arg.MenuIds,
		arg.Quantities,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
