// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCartByGuestIDAndStoreID = `-- name: GetCartByGuestIDAndStoreID :many
SELECT
    carts.id AS cart_id,
    carts.guest_id,
    carts.store_id,

    cart_items.id AS cart_item_id,
    cart_items.quantity AS cart_item_quantity,
    cart_items.created_at AS cart_item_created_at,

    menus.id AS menu_id,
    menus.name AS menu_name,
    menus.unit_price AS menu_unit_price,
    menus.image_object_key AS menu_image_object_key,
    menus.sold_out AS menu_sold_out,
    menus.deleted_at AS menu_deleted_at,

    cart_item_toppings.id AS cart_item_topping_id,

    toppings.id AS topping_id,
    toppings.name AS topping_name,
    toppings.unit_price AS topping_unit_price,
    toppings.sold_out AS topping_sold_out,
    toppings.deleted_at AS topping_deleted_at
FROM carts
INNER JOIN cart_items
    ON cart_items.cart_id = carts.id
    AND cart_items.store_id = carts.store_id
INNER JOIN menus
    ON menus.id = cart_items.menu_id
    AND menus.store_id = cart_items.store_id
LEFT JOIN cart_item_toppings
    ON cart_item_toppings.cart_item_id = cart_items.id
    AND cart_item_toppings.menu_id = cart_items.menu_id
LEFT JOIN toppings
    ON toppings.id = cart_item_toppings.topping_id
WHERE carts.guest_id = $1
  AND carts.store_id = $2
ORDER BY
    cart_items.created_at ASC,
    cart_items.id ASC,
    toppings.id ASC
`

type GetCartByGuestIDAndStoreIDParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type GetCartByGuestIDAndStoreIDRow struct {
	CartID             uuid.UUID          `json:"cart_id"`
	GuestID            uuid.UUID          `json:"guest_id"`
	StoreID            uuid.UUID          `json:"store_id"`
	CartItemID         uuid.UUID          `json:"cart_item_id"`
	CartItemQuantity   int32              `json:"cart_item_quantity"`
	CartItemCreatedAt  pgtype.Timestamptz `json:"cart_item_created_at"`
	MenuID             uuid.UUID          `json:"menu_id"`
	MenuName           string             `json:"menu_name"`
	MenuUnitPrice      int32              `json:"menu_unit_price"`
	MenuImageObjectKey string             `json:"menu_image_object_key"`
	MenuSoldOut        bool               `json:"menu_sold_out"`
	MenuDeletedAt      pgtype.Timestamptz `json:"menu_deleted_at"`
	CartItemToppingID  *uuid.UUID         `json:"cart_item_topping_id"`
	ToppingID          *uuid.UUID         `json:"topping_id"`
	ToppingName        *string            `json:"topping_name"`
	ToppingUnitPrice   *int32             `json:"topping_unit_price"`
	ToppingSoldOut     *bool              `json:"topping_sold_out"`
	ToppingDeletedAt   pgtype.Timestamptz `json:"topping_deleted_at"`
}

func (q *Queries) GetCartByGuestIDAndStoreID(ctx context.Context, arg GetCartByGuestIDAndStoreIDParams) ([]GetCartByGuestIDAndStoreIDRow, error) {
	rows, err := q.db.Query(ctx, getCartByGuestIDAndStoreID, arg.GuestID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartByGuestIDAndStoreIDRow{}
	for rows.Next() {
		var i GetCartByGuestIDAndStoreIDRow
		if err := rows.Scan(
			&i.CartID,
			&i.GuestID,
			&i.StoreID,
			&i.CartItemID,
			&i.CartItemQuantity,
			&i.CartItemCreatedAt,
			&i.MenuID,
			&i.MenuName,
			&i.MenuUnitPrice,
			&i.MenuImageObjectKey,
			&i.MenuSoldOut,
			&i.MenuDeletedAt,
			&i.CartItemToppingID,
			&i.ToppingID,
			&i.ToppingName,
			&i.ToppingUnitPrice,
			&i.ToppingSoldOut,
			&i.ToppingDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
