// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateGuest(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createGuest)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
