// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addAllergensToMenu = `-- name: AddAllergensToMenu :exec
INSERT INTO menu_allergens (
    menu_id,
    allergen_id
)
SELECT
    $1,
    ids.allergen_id
FROM unnest($2::uuid[]) AS ids(allergen_id)
ON CONFLICT (menu_id, allergen_id) DO NOTHING
`

type AddAllergensToMenuParams struct {
	MenuID      uuid.UUID   `json:"menu_id"`
	AllergenIds []uuid.UUID `json:"allergen_ids"`
}

func (q *Queries) AddAllergensToMenu(ctx context.Context, arg AddAllergensToMenuParams) error {
	_, err := q.db.Exec(ctx, addAllergensToMenu, arg.MenuID, arg.AllergenIds)
	return err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (
    id,
    store_id,
    name,
    description,
    unit_price,
    image_object_key
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, store_id, name, description, unit_price, image_object_key, sold_out, deleted_at, updated_at, created_at
`

type CreateMenuParams struct {
	ID             uuid.UUID `json:"id"`
	StoreID        uuid.UUID `json:"store_id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	UnitPrice      int32     `json:"unit_price"`
	ImageObjectKey string    `json:"image_object_key"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.ImageObjectKey,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.ImageObjectKey,
		&i.SoldOut,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMenusByStoreID = `-- name: GetMenusByStoreID :many
SELECT id, store_id, name, description, unit_price, image_object_key, sold_out, deleted_at, updated_at, created_at
FROM menus
WHERE store_id = $1
    AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

func (q *Queries) GetMenusByStoreID(ctx context.Context, storeID uuid.UUID) ([]Menu, error) {
	rows, err := q.db.Query(ctx, getMenusByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Menu{}
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.ImageObjectKey,
			&i.SoldOut,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
