// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_topipngs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMenuToppings = `-- name: CreateMenuToppings :exec
INSERT INTO menu_toppings (
    menu_id,
    topping_id,
    store_id
)
SELECT
    $1,
    ids.topping_id,
    $2
FROM unnest($3::uuid[]) AS ids(topping_id)
`

type CreateMenuToppingsParams struct {
	MenuID     uuid.UUID   `json:"menu_id"`
	StoreID    uuid.UUID   `json:"store_id"`
	ToppingIds []uuid.UUID `json:"topping_ids"`
}

func (q *Queries) CreateMenuToppings(ctx context.Context, arg CreateMenuToppingsParams) error {
	_, err := q.db.Exec(ctx, createMenuToppings, arg.MenuID, arg.StoreID, arg.ToppingIds)
	return err
}
