// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusCompleted OrderStatus = "completed"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Role string

const (
	RoleMember Role = "member"
	RoleAdmin  Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type StoreMemberRole string

const (
	StoreMemberRoleManager StoreMemberRole = "manager"
	StoreMemberRoleStaff   StoreMemberRole = "staff"
)

func (e *StoreMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoreMemberRole(s)
	case string:
		*e = StoreMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StoreMemberRole: %T", src)
	}
	return nil
}

type NullStoreMemberRole struct {
	StoreMemberRole StoreMemberRole `json:"store_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if StoreMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoreMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.StoreMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoreMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoreMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoreMemberRole), nil
}

type StoreReviewStatus string

const (
	StoreReviewStatusPending  StoreReviewStatus = "pending"
	StoreReviewStatusApproved StoreReviewStatus = "approved"
	StoreReviewStatusRejected StoreReviewStatus = "rejected"
)

func (e *StoreReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoreReviewStatus(s)
	case string:
		*e = StoreReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StoreReviewStatus: %T", src)
	}
	return nil
}

type NullStoreReviewStatus struct {
	StoreReviewStatus StoreReviewStatus `json:"store_review_status"`
	Valid             bool              `json:"valid"` // Valid is true if StoreReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoreReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StoreReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoreReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoreReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoreReviewStatus), nil
}

type Account struct {
	ID          uuid.UUID          `json:"id"`
	GoogleSub   string             `json:"google_sub"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	PictureUrl  *string            `json:"picture_url"`
	Role        Role               `json:"role"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AccountSession struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Allergen struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Cart struct {
	ID      uuid.UUID `json:"id"`
	GuestID uuid.UUID `json:"guest_id"`
	StoreID uuid.UUID `json:"store_id"`
	Version int32     `json:"version"`
}

type CartItem struct {
	ID        uuid.UUID          `json:"id"`
	CartID    uuid.UUID          `json:"cart_id"`
	MenuID    uuid.UUID          `json:"menu_id"`
	StoreID   uuid.UUID          `json:"store_id"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CartItemTopping struct {
	ID         uuid.UUID `json:"id"`
	CartItemID uuid.UUID `json:"cart_item_id"`
	MenuID     uuid.UUID `json:"menu_id"`
	ToppingID  uuid.UUID `json:"topping_id"`
}

type Guest struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GuestSession struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Menu struct {
	ID             uuid.UUID          `json:"id"`
	StoreID        uuid.UUID          `json:"store_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	UnitPrice      int32              `json:"unit_price"`
	ImageObjectKey string             `json:"image_object_key"`
	SoldOut        bool               `json:"sold_out"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MenuTopping struct {
	MenuID    uuid.UUID `json:"menu_id"`
	ToppingID uuid.UUID `json:"topping_id"`
	StoreID   uuid.UUID `json:"store_id"`
}

type Order struct {
	ID                       uuid.UUID          `json:"id"`
	StoreID                  uuid.UUID          `json:"store_id"`
	GuestID                  uuid.UUID          `json:"guest_id"`
	Status                   OrderStatus        `json:"status"`
	TotalAmount              int64              `json:"total_amount"`
	DisplayNumber            int32              `json:"display_number"`
	Version                  int32              `json:"version"`
	OriginCartID             uuid.UUID          `json:"origin_cart_id"`
	OriginCartVersion        int32              `json:"origin_cart_version"`
	LimitExemptedByAccountID *uuid.UUID         `json:"limit_exempted_by_account_id"`
	StoreName                string             `json:"store_name"`
	RoomName                 string             `json:"room_name"`
	ReadyAt                  pgtype.Timestamptz `json:"ready_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	StoreID   uuid.UUID `json:"store_id"`
	MenuID    uuid.UUID `json:"menu_id"`
	MenuName  string    `json:"menu_name"`
	UnitPrice int32     `json:"unit_price"`
	Quantity  int32     `json:"quantity"`
}

type OrderItemTopping struct {
	OrderItemID uuid.UUID `json:"order_item_id"`
	StoreID     uuid.UUID `json:"store_id"`
	ToppingID   uuid.UUID `json:"topping_id"`
	ToppingName string    `json:"topping_name"`
	UnitPrice   int32     `json:"unit_price"`
}

type Review struct {
	ID        uuid.UUID          `json:"id"`
	GuestID   *uuid.UUID         `json:"guest_id"`
	AccountID *uuid.UUID         `json:"account_id"`
	Rating    int32              `json:"rating"`
	Comment   *string            `json:"comment"`
	Trigger   *string            `json:"trigger"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	Name      string `json:"name"`
	SortOrder int16  `json:"sort_order"`
}

type Store struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Room            string             `json:"room"`
	Description     string             `json:"description"`
	ImageObjectKey  string             `json:"image_object_key"`
	ReviewStatus    StoreReviewStatus  `json:"review_status"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	CongestionLevel int32              `json:"congestion_level"`
}

type StoreAllergen struct {
	StoreID    uuid.UUID `json:"store_id"`
	AllergenID uuid.UUID `json:"allergen_id"`
}

type StoreInvitation struct {
	ID        uuid.UUID          `json:"id"`
	StoreID   uuid.UUID          `json:"store_id"`
	Role      StoreMemberRole    `json:"role"`
	MaxUses   *int32             `json:"max_uses"`
	UseCount  int32              `json:"use_count"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StoreMember struct {
	StoreID   uuid.UUID          `json:"store_id"`
	AccountID uuid.UUID          `json:"account_id"`
	Role      StoreMemberRole    `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type StoreOrderCounter struct {
	StoreID    uuid.UUID `json:"store_id"`
	LastNumber int32     `json:"last_number"`
}

type Topping struct {
	ID        uuid.UUID          `json:"id"`
	StoreID   uuid.UUID          `json:"store_id"`
	Name      string             `json:"name"`
	UnitPrice int32              `json:"unit_price"`
	SoldOut   bool               `json:"sold_out"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
