// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countActiveNonExemptOrders = `-- name: CountActiveNonExemptOrders :one
SELECT count(*) FROM orders
WHERE guest_id = $1 AND status IN ('pending', 'ready')
  AND limit_exempted_by_account_id IS NULL
`

func (q *Queries) CountActiveNonExemptOrders(ctx context.Context, guestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveNonExemptOrders, guestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    store_id, guest_id, total_amount, display_number,
    origin_cart_id, origin_cart_version, limit_exempted_by_account_id,
    store_name, room_name
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
) RETURNING id, store_id, guest_id, status, total_amount, display_number, version, origin_cart_id, origin_cart_version, limit_exempted_by_account_id, store_name, room_name, ready_at, completed_at, cancelled_at, created_at, updated_at
`

type CreateOrderParams struct {
	StoreID                  uuid.UUID  `json:"store_id"`
	GuestID                  uuid.UUID  `json:"guest_id"`
	TotalAmount              int64      `json:"total_amount"`
	DisplayNumber            int32      `json:"display_number"`
	OriginCartID             uuid.UUID  `json:"origin_cart_id"`
	OriginCartVersion        int32      `json:"origin_cart_version"`
	LimitExemptedByAccountID *uuid.UUID `json:"limit_exempted_by_account_id"`
	StoreName                string     `json:"store_name"`
	RoomName                 string     `json:"room_name"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.StoreID,
		arg.GuestID,
		arg.TotalAmount,
		arg.DisplayNumber,
		arg.OriginCartID,
		arg.OriginCartVersion,
		arg.LimitExemptedByAccountID,
		arg.StoreName,
		arg.RoomName,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.GuestID,
		&i.Status,
		&i.TotalAmount,
		&i.DisplayNumber,
		&i.Version,
		&i.OriginCartID,
		&i.OriginCartVersion,
		&i.LimitExemptedByAccountID,
		&i.StoreName,
		&i.RoomName,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, store_id, menu_id, menu_name, unit_price, quantity)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, order_id, store_id, menu_id, menu_name, unit_price, quantity
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	StoreID   uuid.UUID `json:"store_id"`
	MenuID    uuid.UUID `json:"menu_id"`
	MenuName  string    `json:"menu_name"`
	UnitPrice int32     `json:"unit_price"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.StoreID,
		arg.MenuID,
		arg.MenuName,
		arg.UnitPrice,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.StoreID,
		&i.MenuID,
		&i.MenuName,
		&i.UnitPrice,
		&i.Quantity,
	)
	return i, err
}

const createOrderItemTopping = `-- name: CreateOrderItemTopping :exec
INSERT INTO order_item_toppings (order_item_id, store_id, topping_id, topping_name, unit_price)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemToppingParams struct {
	OrderItemID uuid.UUID `json:"order_item_id"`
	StoreID     uuid.UUID `json:"store_id"`
	ToppingID   uuid.UUID `json:"topping_id"`
	ToppingName string    `json:"topping_name"`
	UnitPrice   int32     `json:"unit_price"`
}

func (q *Queries) CreateOrderItemTopping(ctx context.Context, arg CreateOrderItemToppingParams) error {
	_, err := q.db.Exec(ctx, createOrderItemTopping,
		arg.OrderItemID,
		arg.StoreID,
		arg.ToppingID,
		arg.ToppingName,
		arg.UnitPrice,
	)
	return err
}

const findOrderForCartVersion = `-- name: FindOrderForCartVersion :one
SELECT orders.id, orders.store_id, orders.guest_id, orders.status, orders.total_amount, orders.display_number, orders.version, orders.origin_cart_id, orders.origin_cart_version, orders.limit_exempted_by_account_id, orders.store_name, orders.room_name, orders.ready_at, orders.completed_at, orders.cancelled_at, orders.created_at, orders.updated_at FROM orders
JOIN carts ON carts.id = orders.origin_cart_id
WHERE carts.guest_id = $1
  AND carts.store_id = $2
  AND orders.origin_cart_version = $3
`

type FindOrderForCartVersionParams struct {
	GuestID     uuid.UUID `json:"guest_id"`
	StoreID     uuid.UUID `json:"store_id"`
	CartVersion int32     `json:"cart_version"`
}

// Guestロックの後、現在の販売状況を検証する前に再送を解決する。
func (q *Queries) FindOrderForCartVersion(ctx context.Context, arg FindOrderForCartVersionParams) (Order, error) {
	row := q.db.QueryRow(ctx, findOrderForCartVersion, arg.GuestID, arg.StoreID, arg.CartVersion)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.GuestID,
		&i.Status,
		&i.TotalAmount,
		&i.DisplayNumber,
		&i.Version,
		&i.OriginCartID,
		&i.OriginCartVersion,
		&i.LimitExemptedByAccountID,
		&i.StoreName,
		&i.RoomName,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreatedOrderItemToppings = `-- name: GetCreatedOrderItemToppings :many
SELECT order_item_toppings.order_item_id, order_item_toppings.store_id, order_item_toppings.topping_id, order_item_toppings.topping_name, order_item_toppings.unit_price FROM order_item_toppings
JOIN order_items ON order_items.id = order_item_toppings.order_item_id
WHERE order_items.order_id = $1 ORDER BY order_item_id, topping_id
`

func (q *Queries) GetCreatedOrderItemToppings(ctx context.Context, orderID uuid.UUID) ([]OrderItemTopping, error) {
	rows, err := q.db.Query(ctx, getCreatedOrderItemToppings, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemTopping{}
	for rows.Next() {
		var i OrderItemTopping
		if err := rows.Scan(
			&i.OrderItemID,
			&i.StoreID,
			&i.ToppingID,
			&i.ToppingName,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreatedOrderItems = `-- name: GetCreatedOrderItems :many
SELECT id, order_id, store_id, menu_id, menu_name, unit_price, quantity FROM order_items WHERE order_id = $1 ORDER BY id
`

func (q *Queries) GetCreatedOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getCreatedOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.StoreID,
			&i.MenuID,
			&i.MenuName,
			&i.UnitPrice,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderCart = `-- name: LockOrderCart :one
SELECT id, guest_id, store_id, version FROM carts
WHERE guest_id = $1 AND store_id = $2
FOR UPDATE
`

type LockOrderCartParams struct {
	GuestID uuid.UUID `json:"guest_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) LockOrderCart(ctx context.Context, arg LockOrderCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, lockOrderCart, arg.GuestID, arg.StoreID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.StoreID,
		&i.Version,
	)
	return i, err
}

const lockOrderMembership = `-- name: LockOrderMembership :one
SELECT store_id, account_id, role, joined_at FROM store_members
WHERE store_id = $1 AND account_id = $2
FOR UPDATE
`

type LockOrderMembershipParams struct {
	StoreID   uuid.UUID `json:"store_id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) LockOrderMembership(ctx context.Context, arg LockOrderMembershipParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, lockOrderMembership, arg.StoreID, arg.AccountID)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const nextOrderDisplayNumber = `-- name: NextOrderDisplayNumber :one
INSERT INTO store_order_counters (store_id, last_number) VALUES ($1, 1)
ON CONFLICT (store_id) DO UPDATE
SET last_number = store_order_counters.last_number + 1
RETURNING last_number
`

func (q *Queries) NextOrderDisplayNumber(ctx context.Context, storeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextOrderDisplayNumber, storeID)
	var last_number int32
	err := row.Scan(&last_number)
	return last_number, err
}
