// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (guest_id, account_id, rating, comment, trigger)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guest_id, account_id, rating, comment, trigger, created_at
`

type CreateReviewParams struct {
	GuestID   *uuid.UUID `json:"guest_id"`
	AccountID *uuid.UUID `json:"account_id"`
	Rating    int32      `json:"rating"`
	Comment   *string    `json:"comment"`
	Trigger   *string    `json:"trigger"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.GuestID,
		arg.AccountID,
		arg.Rating,
		arg.Comment,
		arg.Trigger,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.AccountID,
		&i.Rating,
		&i.Comment,
		&i.Trigger,
		&i.CreatedAt,
	)
	return i, err
}
