// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"
)

const getRoomByName = `-- name: GetRoomByName :one
SELECT name, sort_order
FROM rooms
WHERE name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByName, name)
	var i Room
	err := row.Scan(&i.Name, &i.SortOrder)
	return i, err
}

const getRooms = `-- name: GetRooms :many
SELECT name, sort_order
FROM rooms
ORDER BY sort_order, name
`

func (q *Queries) GetRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
