// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createStoreMember = `-- name: CreateStoreMember :one
INSERT INTO store_members (
    store_id,
    account_id,
    role
) VALUES (
    $1, $2, $3
)
RETURNING store_id, account_id, role, joined_at
`

type CreateStoreMemberParams struct {
	StoreID   uuid.UUID       `json:"store_id"`
	AccountID uuid.UUID       `json:"account_id"`
	Role      StoreMemberRole `json:"role"`
}

func (q *Queries) CreateStoreMember(ctx context.Context, arg CreateStoreMemberParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, createStoreMember, arg.StoreID, arg.AccountID, arg.Role)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createStoreMemberIfNotExists = `-- name: CreateStoreMemberIfNotExists :one
INSERT INTO store_members (
    store_id,
    account_id,
    role
) VALUES (
    $1, $2, $3
)
ON CONFLICT (store_id, account_id) DO NOTHING
RETURNING store_id, account_id, role, joined_at
`

type CreateStoreMemberIfNotExistsParams struct {
	StoreID   uuid.UUID       `json:"store_id"`
	AccountID uuid.UUID       `json:"account_id"`
	Role      StoreMemberRole `json:"role"`
}

func (q *Queries) CreateStoreMemberIfNotExists(ctx context.Context, arg CreateStoreMemberIfNotExistsParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, createStoreMemberIfNotExists, arg.StoreID, arg.AccountID, arg.Role)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getStoreMemberByAccountIDAndStoreID = `-- name: GetStoreMemberByAccountIDAndStoreID :one
SELECT store_id, account_id, role, joined_at
FROM store_members
WHERE account_id = $1 AND store_id = $2
`

type GetStoreMemberByAccountIDAndStoreIDParams struct {
	AccountID uuid.UUID `json:"account_id"`
	StoreID   uuid.UUID `json:"store_id"`
}

func (q *Queries) GetStoreMemberByAccountIDAndStoreID(ctx context.Context, arg GetStoreMemberByAccountIDAndStoreIDParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, getStoreMemberByAccountIDAndStoreID, arg.AccountID, arg.StoreID)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
