// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getStoreMemberByAccountIDAndStoreID = `-- name: GetStoreMemberByAccountIDAndStoreID :one
SELECT store_id, account_id, role, joined_at
FROM store_members
WHERE account_id = $1 AND store_id = $2
`

type GetStoreMemberByAccountIDAndStoreIDParams struct {
	AccountID uuid.UUID `json:"account_id"`
	StoreID   uuid.UUID `json:"store_id"`
}

func (q *Queries) GetStoreMemberByAccountIDAndStoreID(ctx context.Context, arg GetStoreMemberByAccountIDAndStoreIDParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, getStoreMemberByAccountIDAndStoreID, arg.AccountID, arg.StoreID)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
