// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreMember = `-- name: CreateStoreMember :one
INSERT INTO store_members (
    store_id,
    account_id,
    role
) VALUES (
    $1, $2, $3
)
RETURNING store_id, account_id, role, joined_at
`

type CreateStoreMemberParams struct {
	StoreID   uuid.UUID       `json:"store_id"`
	AccountID uuid.UUID       `json:"account_id"`
	Role      StoreMemberRole `json:"role"`
}

func (q *Queries) CreateStoreMember(ctx context.Context, arg CreateStoreMemberParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, createStoreMember, arg.StoreID, arg.AccountID, arg.Role)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createStoreMemberIfNotExists = `-- name: CreateStoreMemberIfNotExists :one
INSERT INTO store_members (
    store_id,
    account_id,
    role
) VALUES (
    $1, $2, $3
)
ON CONFLICT (store_id, account_id) DO NOTHING
RETURNING store_id, account_id, role, joined_at
`

type CreateStoreMemberIfNotExistsParams struct {
	StoreID   uuid.UUID       `json:"store_id"`
	AccountID uuid.UUID       `json:"account_id"`
	Role      StoreMemberRole `json:"role"`
}

func (q *Queries) CreateStoreMemberIfNotExists(ctx context.Context, arg CreateStoreMemberIfNotExistsParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, createStoreMemberIfNotExists, arg.StoreID, arg.AccountID, arg.Role)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getStoreMemberByAccountIDAndStoreID = `-- name: GetStoreMemberByAccountIDAndStoreID :one
SELECT store_id, account_id, role, joined_at
FROM store_members
WHERE account_id = $1 AND store_id = $2
`

type GetStoreMemberByAccountIDAndStoreIDParams struct {
	AccountID uuid.UUID `json:"account_id"`
	StoreID   uuid.UUID `json:"store_id"`
}

func (q *Queries) GetStoreMemberByAccountIDAndStoreID(ctx context.Context, arg GetStoreMemberByAccountIDAndStoreIDParams) (StoreMember, error) {
	row := q.db.QueryRow(ctx, getStoreMemberByAccountIDAndStoreID, arg.AccountID, arg.StoreID)
	var i StoreMember
	err := row.Scan(
		&i.StoreID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getStoreMembersByStoreID = `-- name: GetStoreMembersByStoreID :many
SELECT store_id, account_id, store_members.role, joined_at, id, google_sub, email, display_name, picture_url, accounts.role, last_login_at, created_at, updated_at
FROM store_members
INNER JOIN accounts
    ON store_members.account_id = accounts.id
WHERE store_members.store_id = $1
ORDER BY store_members.joined_at ASC
`

type GetStoreMembersByStoreIDRow struct {
	StoreID     uuid.UUID          `json:"store_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	Role        StoreMemberRole    `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	ID          uuid.UUID          `json:"id"`
	GoogleSub   string             `json:"google_sub"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	PictureUrl  *string            `json:"picture_url"`
	Role_2      Role               `json:"role_2"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetStoreMembersByStoreID(ctx context.Context, storeID uuid.UUID) ([]GetStoreMembersByStoreIDRow, error) {
	rows, err := q.db.Query(ctx, getStoreMembersByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStoreMembersByStoreIDRow{}
	for rows.Next() {
		var i GetStoreMembersByStoreIDRow
		if err := rows.Scan(
			&i.StoreID,
			&i.AccountID,
			&i.Role,
			&i.JoinedAt,
			&i.ID,
			&i.GoogleSub,
			&i.Email,
			&i.DisplayName,
			&i.PictureUrl,
			&i.Role_2,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
