// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addAllergensToStore = `-- name: AddAllergensToStore :exec

INSERT INTO store_allergens (
    store_id,
    allergen_id
)
SELECT
    $1,
    ids.allergen_id
FROM unnest($2::uuid[]) AS ids(allergen_id)
ON CONFLICT (store_id, allergen_id) DO NOTHING
`

type AddAllergensToStoreParams struct {
	StoreID     uuid.UUID   `json:"store_id"`
	AllergenIds []uuid.UUID `json:"allergen_ids"`
}

// pending からしか遷移できないので pending の場合のみ更新する
func (q *Queries) AddAllergensToStore(ctx context.Context, arg AddAllergensToStoreParams) error {
	_, err := q.db.Exec(ctx, addAllergensToStore, arg.StoreID, arg.AllergenIds)
	return err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    id,
    name,
    room,
    description,
    image_object_key,
    review_status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
`

type CreateStoreParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Room           string    `json:"room"`
	Description    string    `json:"description"`
	ImageObjectKey string    `json:"image_object_key"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.ID,
		arg.Name,
		arg.Room,
		arg.Description,
		arg.ImageObjectKey,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteAllStoreAllergens = `-- name: DeleteAllStoreAllergens :exec
DELETE FROM store_allergens
WHERE store_id = $1
`

func (q *Queries) DeleteAllStoreAllergens(ctx context.Context, storeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllStoreAllergens, storeID)
	return err
}

const getApprovedStoreByID = `-- name: GetApprovedStoreByID :one
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
FROM stores
WHERE review_status = 'approved'
    AND id = $1
`

func (q *Queries) GetApprovedStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getApprovedStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getApprovedStores = `-- name: GetApprovedStores :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
FROM stores
WHERE review_status = 'approved'
ORDER BY created_at DESC
`

func (q *Queries) GetApprovedStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, getApprovedStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberStoresByAccountID = `-- name: GetMemberStoresByAccountID :many
SELECT stores.id, stores.name, stores.room, stores.description, stores.image_object_key, stores.review_status, stores.submitted_at, stores.created_at, stores.updated_at, stores.closed_at
FROM stores
JOIN store_members ON store_members.store_id = stores.id
WHERE store_members.account_id = $1
  AND stores.review_status IN ('approved', 'pending')
ORDER BY stores.created_at DESC
`

func (q *Queries) GetMemberStoresByAccountID(ctx context.Context, accountID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getMemberStoresByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreApplications = `-- name: GetStoreApplications :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
FROM stores
WHERE review_status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) GetStoreApplications(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, getStoreApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
FROM stores
WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getVisibleStoresByAccountID = `-- name: GetVisibleStoresByAccountID :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
FROM stores
WHERE review_status = 'approved'
   OR (
       review_status = 'pending'
       AND id IN (
           SELECT store_id
           FROM store_members
           WHERE account_id = $1
             AND role = 'manager'
       )
   )
ORDER BY created_at DESC
`

func (q *Queries) GetVisibleStoresByAccountID(ctx context.Context, accountID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getVisibleStoresByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET
    closed_at = CASE
        WHEN $1::boolean IS NULL THEN closed_at
        WHEN $1::boolean THEN COALESCE(closed_at, now())
        ELSE NULL
    END,
    room = COALESCE($2::text, room),
    description = COALESCE($3::text, description),
    image_object_key = COALESCE($4::text, image_object_key),
    updated_at = now()
WHERE id = $5
    AND review_status = 'approved'
RETURNING id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at, closed_at
`

type UpdateStoreParams struct {
	Closed         *bool     `json:"closed"`
	Room           *string   `json:"room"`
	Description    *string   `json:"description"`
	ImageObjectKey *string   `json:"image_object_key"`
	StoreID        uuid.UUID `json:"store_id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.Closed,
		arg.Room,
		arg.Description,
		arg.ImageObjectKey,
		arg.StoreID,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateStoreReviewStatusById = `-- name: UpdateStoreReviewStatusById :exec
UPDATE stores
SET
    review_status = $2,
    updated_at = now()
WHERE id = $1
    AND review_status = 'pending'
`

type UpdateStoreReviewStatusByIdParams struct {
	ID           uuid.UUID         `json:"id"`
	ReviewStatus StoreReviewStatus `json:"review_status"`
}

func (q *Queries) UpdateStoreReviewStatusById(ctx context.Context, arg UpdateStoreReviewStatusByIdParams) error {
	_, err := q.db.Exec(ctx, updateStoreReviewStatusById, arg.ID, arg.ReviewStatus)
	return err
}
