// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createStoreInvitation = `-- name: CreateStoreInvitation :one
INSERT INTO store_invitations (
    store_id,
    role,
    max_uses
) VALUES (
    $1, $2, $3
)
RETURNING id, store_id, role, max_uses, use_count, updated_at, created_at
`

type CreateStoreInvitationParams struct {
	StoreID uuid.UUID       `json:"store_id"`
	Role    StoreMemberRole `json:"role"`
	MaxUses *int32          `json:"max_uses"`
}

func (q *Queries) CreateStoreInvitation(ctx context.Context, arg CreateStoreInvitationParams) (StoreInvitation, error) {
	row := q.db.QueryRow(ctx, createStoreInvitation, arg.StoreID, arg.Role, arg.MaxUses)
	var i StoreInvitation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Role,
		&i.MaxUses,
		&i.UseCount,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStoreInvitationByID = `-- name: GetStoreInvitationByID :one
SELECT id, store_id, role, max_uses, use_count, updated_at, created_at
FROM store_invitations
WHERE id = $1
`

func (q *Queries) GetStoreInvitationByID(ctx context.Context, id uuid.UUID) (StoreInvitation, error) {
	row := q.db.QueryRow(ctx, getStoreInvitationByID, id)
	var i StoreInvitation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Role,
		&i.MaxUses,
		&i.UseCount,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementStoreInvitationUseCount = `-- name: IncrementStoreInvitationUseCount :one
UPDATE store_invitations
SET
    use_count = use_count + 1,
    updated_at = now()
WHERE id = $1
  AND (
      max_uses IS NULL -- max_uses が NULL の場合は無制限に使用可能
      OR use_count < max_uses
  )
RETURNING id, store_id, role, max_uses, use_count, updated_at, created_at
`

func (q *Queries) IncrementStoreInvitationUseCount(ctx context.Context, id uuid.UUID) (StoreInvitation, error) {
	row := q.db.QueryRow(ctx, incrementStoreInvitationUseCount, id)
	var i StoreInvitation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Role,
		&i.MaxUses,
		&i.UseCount,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
