// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addAllergensToStore = `-- name: AddAllergensToStore :exec

INSERT INTO store_allergens (
    store_id,
    allergen_id
)
SELECT
    $1,
    ids.allergen_id
FROM unnest($2::uuid[]) AS ids(allergen_id)
ON CONFLICT (store_id, allergen_id) DO NOTHING
`

type AddAllergensToStoreParams struct {
	StoreID     uuid.UUID   `json:"store_id"`
	AllergenIds []uuid.UUID `json:"allergen_ids"`
}

// pending からしか遷移できないので pending の場合のみ更新する
func (q *Queries) AddAllergensToStore(ctx context.Context, arg AddAllergensToStoreParams) error {
	_, err := q.db.Exec(ctx, addAllergensToStore, arg.StoreID, arg.AllergenIds)
	return err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    id,
    name,
    room,
    description,
    image_object_key,
    review_status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
`

type CreateStoreParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Room           string    `json:"room"`
	Description    string    `json:"description"`
	ImageObjectKey string    `json:"image_object_key"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.ID,
		arg.Name,
		arg.Room,
		arg.Description,
		arg.ImageObjectKey,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedStoreByID = `-- name: GetApprovedStoreByID :one
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
FROM stores
WHERE review_status = 'approved'
    AND id = $1
`

func (q *Queries) GetApprovedStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getApprovedStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedStores = `-- name: GetApprovedStores :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
FROM stores
WHERE review_status = 'approved'
ORDER BY created_at DESC
`

func (q *Queries) GetApprovedStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, getApprovedStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreApplications = `-- name: GetStoreApplications :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
FROM stores
WHERE review_status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) GetStoreApplications(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, getStoreApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
FROM stores
WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Room,
		&i.Description,
		&i.ImageObjectKey,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleStoresByAccountID = `-- name: GetVisibleStoresByAccountID :many
SELECT id, name, room, description, image_object_key, review_status, submitted_at, created_at, updated_at
FROM stores
WHERE review_status = 'approved'
   OR id IN (
       SELECT store_id
       FROM store_members
       WHERE account_id = $1
         AND role = 'manager'
   )
ORDER BY created_at DESC
`

func (q *Queries) GetVisibleStoresByAccountID(ctx context.Context, accountID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getVisibleStoresByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Room,
			&i.Description,
			&i.ImageObjectKey,
			&i.ReviewStatus,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreReviewStatusById = `-- name: UpdateStoreReviewStatusById :exec
UPDATE stores
SET
    review_status = $2,
    updated_at = now()
WHERE id = $1
    AND review_status = 'pending'
`

type UpdateStoreReviewStatusByIdParams struct {
	ID           uuid.UUID         `json:"id"`
	ReviewStatus StoreReviewStatus `json:"review_status"`
}

func (q *Queries) UpdateStoreReviewStatusById(ctx context.Context, arg UpdateStoreReviewStatusByIdParams) error {
	_, err := q.db.Exec(ctx, updateStoreReviewStatusById, arg.ID, arg.ReviewStatus)
	return err
}
