// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: toppings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getToppingsByStoreID = `-- name: GetToppingsByStoreID :many
SELECT id, store_id, name, description, unit_price, sold_out, deleted_at, updated_at, created_at
FROM toppings
WHERE store_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetToppingsByStoreID(ctx context.Context, storeID uuid.UUID) ([]Topping, error) {
	rows, err := q.db.Query(ctx, getToppingsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topping{}
	for rows.Next() {
		var i Topping
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.SoldOut,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
