// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: toppings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTopping = `-- name: CreateTopping :one
INSERT INTO toppings (
    store_id,
    name,
    unit_price
) VALUES (
    $1, $2, $3
)
RETURNING id, store_id, name, unit_price, sold_out, deleted_at, updated_at, created_at
`

type CreateToppingParams struct {
	StoreID   uuid.UUID `json:"store_id"`
	Name      string    `json:"name"`
	UnitPrice int32     `json:"unit_price"`
}

func (q *Queries) CreateTopping(ctx context.Context, arg CreateToppingParams) (Topping, error) {
	row := q.db.QueryRow(ctx, createTopping, arg.StoreID, arg.Name, arg.UnitPrice)
	var i Topping
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.UnitPrice,
		&i.SoldOut,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTopping = `-- name: DeleteTopping :execrows
UPDATE toppings
SET deleted_at = NOW()
WHERE id = $1
  AND store_id = $2
`

type DeleteToppingParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) DeleteTopping(ctx context.Context, arg DeleteToppingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTopping, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getToppingsByStoreID = `-- name: GetToppingsByStoreID :many
SELECT id, store_id, name, unit_price, sold_out, deleted_at, updated_at, created_at
FROM toppings
WHERE store_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetToppingsByStoreID(ctx context.Context, storeID uuid.UUID) ([]Topping, error) {
	rows, err := q.db.Query(ctx, getToppingsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topping{}
	for rows.Next() {
		var i Topping
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.UnitPrice,
			&i.SoldOut,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
